### PR TITLE
GH-10162: The full file path for `PersistentAcceptOnceFileListFilter`

### LINKED ISSUE #10162: The `AbstractPersistentAcceptOnceFileListFilter` does not deal with full file name
**In what version(s) of Spring Integration are you seeing this issue?**

6.5.0

**Describe the bug**

SftpClient.DirEntry do not hold the full path of the file.
ScanDirEntry does.

**To Reproduce**

N/A

**Expected behavior**

N/A

**Sample**

N/A

### PR DESCRIPTION
**Pull request by artembilan**
Fixes: https://github.com/spring-projects/spring-integration/issues/10162

The `AbstractPersistentAcceptOnceFileListFilter` may cause a problem with entries in the `MetadataStore` when the same file name is used from different directories. Let's imagine a scenario when remote directories are created every day with respective timestamp, e.g. today `20250828`, tomorrow `20250829`.
 The files in those directories are based on customer names: `customer1.xml`, `customer2.xml` etc.
Since most of the `AbstractPersistentAcceptOnceFileListFilter` implementations do just something like this: `return file.getName();` that would lead to the same key for the `MetadataStore` operations.

* Fix `SmbPersistentAcceptOnceFileListFilter` to use `SmbFile.getUncPath()` as a notation of the full path file
* Fix `SftpPersistentAcceptOnceFileListFilter` to use `SftpClient.DirEntry.getLongFilename()` if it is not empty.
* Fix `SftpSession.list()` to populated the mentioned `longFileName` into a new `SftpClient.DirEntry` instance based on just fetched
* Introduce an `EnhancedFTPFile` adapter to delegate to the original `FTPFile` and populate an additional `longFileName` property
* Check for this new class in the `FtpPersistentAcceptOnceFileListFilter` to extract its `longFileName` property

### CODE REVIEW

File: spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpSession.java [hunk 1]
```diff
@@ -71,7 +74,17 @@ public boolean remove(String path) throws IOException {
 
 	@Override
 	public FTPFile[] list(@Nullable String path) throws IOException {
-		return this.client.listFiles(path);
+		FTPFile[] ftpFiles = this.client.listFiles(path);
+		if (StringUtils.hasText(path)) {
+			List<EnhancedFTPFile> enhancedFtpFiles = new LinkedList<>();
+			for (FTPFile ftpFile : ftpFiles) {
+				EnhancedFTPFile enhancedFTPFile = new EnhancedFTPFile(ftpFile);
+				enhancedFTPFile.setLongFileName(path + '/' + ftpFile.getName());
```
Comment (cppwfs) [inline spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpSession.java]: If path is the Current Working Directory of "" wouldn't we still want to go through the flow of adding the file name?

File: spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpSession.java [hunk 2]
```diff
@@ -71,7 +74,17 @@ public boolean remove(String path) throws IOException {
 
 	@Override
 	public FTPFile[] list(@Nullable String path) throws IOException {
-		return this.client.listFiles(path);
+		FTPFile[] ftpFiles = this.client.listFiles(path);
+		if (StringUtils.hasText(path)) {
+			List<EnhancedFTPFile> enhancedFtpFiles = new LinkedList<>();
```
Comment (cppwfs) [inline spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpSession.java]: Optimization: Since we know the length of the array from line 77 couldn't we allocate an array here and remove the use of the linked list.   Nitpick.

File: spring-integration-ftp/src/test/java/org/springframework/integration/ftp/inbound/FtpInboundRemoteFileSystemSynchronizerTests.java [hunk 3]
```diff
@@ -97,7 +98,7 @@ public void testCopyFileToLocalDir() throws Exception {
 		store.setBaseDirectory("test");
 		store.afterPropertiesSet();
 		FtpPersistentAcceptOnceFileListFilter persistFilter =
-				new FtpPersistentAcceptOnceFileListFilter(store, "foo");
+				new FtpPersistentAcceptOnceFileListFilter(store, "someKey/");
```
Comment (cppwfs) [inline spring-integration-ftp/src/test/java/org/springframework/integration/ftp/inbound/FtpInboundRemoteFileSystemSynchronizerTests.java:101]: Bye bye `foo`. 😄

File: src/reference/antora/modules/ROOT/pages/whats-new.adoc [hunk 4]
```diff
@@ -100,6 +100,11 @@ The `AbstractInboundFileSynchronizer` now caches a filtered result of the `Sessi
 So, later synchronizations deal with the cache only by the `maxFetchSize` until the cache is exhausted.
 See xref:sftp/max-fetch.adoc[] for more information.
 
+All the `AbstractPersistentAcceptOnceFileListFilter` implementations now use a "long file name" for the metadata entry key.
+Perviously, just a file name may cause the metadata overriding problem when the same filter is used for different directories with same file names.
```
Comment (cppwfs) [inline src/reference/antora/modules/ROOT/pages/whats-new.adoc]: Replace `Perviously` with `Previously`

**Review by cppwfs — CHANGES_REQUESTED** [review]
Looks great!  Just my usual nitpicks!

File: spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpSession.java (hunk 1 above)
Comment (artembilan) [reply spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpSession.java]: Do you mean still set `longName` but without a dir prefix?

Comment (cppwfs) [reply spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpSession.java]: Yes.   
I think it would be consistent.   The path still exists, its just... well... empty.

**Comment by cppwfs** [comment]
LGTM.   Thanks for working on this.  It's awesome!
