### PR TITLE
GH-10931: Add setAllowedOriginPatterns support to ServerWebSocketContainer

### LINKED ISSUE #10931: ServerWebSocketContainer.registerWebSocketHandlers() uses setAllowedOrigins() instead of setAllowedOriginPatterns(), causing incompatibility with allowCredentials=true in Spring Framework 7
## Title

`ServerWebSocketContainer.registerWebSocketHandlers()` uses `setAllowedOrigins()` instead of `setAllowedOriginPatterns()`, causing incompatibility with `allowCredentials=true` in Spring Framework 7

---

# Bug Report: ServerWebSocketContainer incompatible with allowCredentials=true in Spring Framework 7

**Repository:** https://github.com/spring-projects/spring-integration  
**Component:** spring-integration-websocket  
**Spring Integration version:** 7.0.4  
**Spring Framework version:** 7.0.6  
**Spring Boot version:** 4.0.5  

---

## Describe the bug

`ServerWebSocketContainer.registerWebSocketHandlers()` internally calls `WebSocketHandlerRegistration.setAllowedOrigins(this.origins)`, which is incompatible with `allowCredentials=true` when the wildcard `"*"` is used. Spring Framework 7 throws:

```
java.lang.IllegalArgumentException: When allowCredentials is true, allowedOrigins
cannot contain the special value "*" since that cannot be set on the
"Access-Control-Allow-Origin" response header. To allow credentials to a set of
origins, list them explicitly or consider using "allowedOriginPatterns" instead.
```

The root cause is in `ServerWebSocketContainer.java` line 168:

```java
public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
    ...
    WebSocketHandlerRegistration registration =
        registry.addHandler(webSocketHandler, this.paths)
                .addInterceptors(this.interceptors)
                .setAllowedOrigins(this.origins);  // <-- should support setAllowedOriginPatterns()
    ...
}
```

`WebSocketHandlerRegistration` has had `setAllowedOriginPatterns()` available since Spring Framework 5.3, but `ServerWebSocketContainer` was never updated to expose or use it.

---

## Steps to reproduce

1. Use Spring Boot 4.0.5 with Spring Integration 7.0.4
2. Configure `ServerWebSocketContainer` with SockJS enabled
3. Have a cross-origin client connect (e.g. UI hosted on a different port)
4. The client sends `GET /messages/info` with an `Origin` header

**Result:** `IllegalArgumentException` thrown by `AbstractSockJsService`, returning HTTP 403 to the client.

**Expected:** The connection succeeds, CORS headers are set correctly.

---

## Stack trace

```
org.springframework.web.socket.sockjs.SockJsException: Uncaught failure in SockJS request,
uri=http://localhost:8081/messages/info
    at ...AbstractSockJsService...
Caused by: java.lang.IllegalArgumentException: When allowCredentials is true,
allowedOrigins cannot contain the special value "*" since that cannot be set on the
"Access-Control-Allow-Origin" response header. To allow credentials to a set of origins,
list them explicitly or consider using "allowedOriginPatterns" instead.
```

---

## Current workaround

Override `registerWebSocketHandlers()` via an anonymous subclass to call `setAllowedOriginPatterns()` directly on the registration:

```java
@Bean
ServerWebSocketContainer serverWebSocketContainer() {
    return new ServerWebSocketContainer("/messages") {
        @Override
        public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
            registry.addHandler(getWebSocketHandler(), "/messages")
                    .setAllowedOriginPatterns("*")
                    .withSockJS()
                    .setSuppressCors(true);
        }
    };
}
```

---

## Suggested fix

1. Add `setAllowedOriginPatterns(String... patterns)` method to `ServerWebSocketContainer`
2. Store the patterns in a separate `private String[] originPatterns` field
3. Update `registerWebSocketHandlers()` to prefer `setAllowedOriginPatterns()` when patterns are configured:

```java
WebSocketHandlerRegistration registration =
    registry.addHandler(webSocketHandler, this.paths)
            .addInterceptors(this.interceptors);

if (this.originPatterns.length > 0) {
    registration.setAllowedOriginPatterns(this.originPatterns);
} else {
    registration.setAllowedOrigins(this.origins);
}
```

### PR DESCRIPTION
**Pull request by marcin-nowicki-pl**
`ServerWebSocketContainer.registerWebSocketHandlers()` hardcoded the use of
`setAllowedOrigins()`, making it impossible to use wildcard patterns (e.g. `"*"`)
together with `allowCredentials=true` in Spring Framework 7+, which forbids that
combination.

This commit adds a `setAllowedOriginPatterns(String...)` method to
`ServerWebSocketContainer` that, when configured, is preferred over
`setAllowedOrigins()` in `registerWebSocketHandlers()`. The existing
`setAllowedOrigins()` behavior is preserved for backward compatibility.

Fixes: #10931

### CODE REVIEW

File: spring-integration-websocket/src/main/java/org/springframework/integration/websocket/ServerWebSocketContainer.java [hunk 1]
```diff
@@ -164,8 +179,14 @@ public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
...
 		WebSocketHandlerRegistration registration =
 				registry.addHandler(webSocketHandler, this.paths)
-						.addInterceptors(this.interceptors)
-						.setAllowedOrigins(this.origins);
+						.addInterceptors(this.interceptors);
+
+		if (!ObjectUtils.isEmpty(this.originPatterns)) {
+			registration.setAllowedOriginPatterns(this.originPatterns);
+		}
+		else {
```
Comment (artembilan) [inline spring-integration-websocket/src/main/java/org/springframework/integration/websocket/ServerWebSocketContainer.java]: I don't think this is correct.
See `AbstractWebSocketHandlerRegistration` logic:
```
		if (!this.allowedOrigins.isEmpty()) {
			this.sockJsServiceRegistration.setAllowedOrigins(StringUtils.toStringArray(this.allowedOrigins));
		}
		if (!this.allowedOriginPatterns.isEmpty()) {
			this.sockJsServiceRegistration.setAllowedOriginPatterns(
					StringUtils.toStringArray(this.allowedOriginPatterns));
		}
```
As well as the target `SockJsServiceRegistration`:
```
service.setAllowedOrigins(this.allowedOrigins);
service.setAllowedOriginPatterns(this.allowedOriginPatterns);
```

Or even `CorsConfiguration`:
```
	public @Nullable String checkOrigin(@Nullable String origin) {
		if (!StringUtils.hasText(origin)) {
			return null;
		}
		String originToCheck = trimTrailingSlash(origin);
		if (!ObjectUtils.isEmpty(this.allowedOrigins)) {
			if (this.allowedOrigins.contains(ALL)) {
				validateAllowCredentials();
				validateAllowPrivateNetwork();
				return ALL;
			}
			for (String allowedOrigin : this.allowedOrigins) {
				if (originToCheck.equalsIgnoreCase(allowedOrigin)) {
					return origin;
				}
			}
		}
		if (!ObjectUtils.isEmpty(this.allowedOriginPatterns)) {
			for (OriginPattern p : this.allowedOriginPatterns) {
				if (p.getDeclaredPattern().equals(ALL) || p.getPattern().matcher(originToCheck).matches()) {
					return origin;
				}
			}
		}
		return null;
	}
```

So, I vote for not `else`, but same as it is done in Spring Framework.

File: spring-integration-websocket/src/main/java/org/springframework/integration/websocket/ServerWebSocketContainer.java [hunk 2]
```diff
@@ -121,6 +124,18 @@ public ServerWebSocketContainer setAllowedOrigins(String... origins) {
 		return this;
 	}
 
+	/**
+	 * Specify origin patterns for which cross-origin requests are allowed from a browser.
+	 * @param originPatterns the origin patterns to allow.
+	 * @return the current ServerWebSocketContainer
+	 * @since 7.1
```
Comment (artembilan) [inline spring-integration-websocket/src/main/java/org/springframework/integration/websocket/ServerWebSocketContainer.java]: We are going to back-port this to `7.0.x`.
Therefore: `7.0.5`

File: spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+ *
+ * @author Marcin Nowicki
+ *
+ * @since 7.1
+ */
+public class ServerWebSocketContainerTests {
+
+	@Test
+	public void setAllowedOriginPatternsIsUsedInRegistration() {
+		WebSocketHandlerRegistry registry = mock(WebSocketHandlerRegistry.class);
```
Comment (artembilan) [inline spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java]: Please, use  just `mock()` without class arg.

File: spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+		WebSocketHandlerRegistration registration = mock(WebSocketHandlerRegistration.class, Answers.RETURNS_SELF);
```
Comment (artembilan) [inline spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java]: DITTO

File: spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+		container.registerWebSocketHandlers(registry);
+
+		verify(registration).setAllowedOriginPatterns("https://example.com");
+		verify(registration, never()).setAllowedOrigins(any());
+	}
+
+	@Test
+	public void setAllowedOriginsIsUsedWhenNoPatternsConfigured() {
+		WebSocketHandlerRegistry registry = mock(WebSocketHandlerRegistry.class);
+		WebSocketHandlerRegistration registration = mock(WebSocketHandlerRegistration.class, Answers.RETURNS_SELF);
```
Comment (artembilan) [inline spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java]: And repeat same type removal in this test, too.

**Review by artembilan — CHANGES_REQUESTED** [review]
Looks promising!

Thank you!

**Comment by marcin-nowicki-pl** [comment]
All changes applied. Thank you for your time and the review!

File: spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+		WebSocketHandlerRegistration registration = mock(Answers.RETURNS_SELF);
+		given(registry.addHandler(any(), any(String[].class))).willReturn(registration);
+
+		ServerWebSocketContainer container = new ServerWebSocketContainer("/test")
+			.setAllowedOrigins("https://example.com");
+
+		container.registerWebSocketHandlers(registry);
+
+		verify(registration).setAllowedOrigins("https://example.com");
+		verify(registration, never()).setAllowedOriginPatterns(any());
```
Comment (artembilan) [inline spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java:68]: ... and one more test when both of them are provided 😄 ?

**Review by artembilan — CHANGES_REQUESTED** [review]

File: spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java (hunk 6 above)
Comment (marcin-nowicki-pl) [reply spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java:68]: right...

File: spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.never;
+import static org.mockito.Mockito.verify;
+
+/**
+ * Tests for {@link ServerWebSocketContainer}.
+ *
+ * @author Marcin Nowicki
+ *
+ * @since 7.1
```
Comment (artembilan) [inline spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java]: Missed this to be changed to `7.0.5`

**Review by artembilan — CHANGES_REQUESTED** [review]

File: spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java (hunk 7 above)
Comment (marcin-nowicki-pl) [reply spring-integration-websocket/src/test/java/org/springframework/integration/websocket/server/ServerWebSocketContainerTests.java]: updated, thanks again for your patience and time, really appreciated!

**Comment by artembilan** [comment]
@marcin-nowicki-pl ,

thank you for contribution; looking forward for more!

**Comment by marcin-nowicki-pl** [comment]
@artembilan ,

Thank you very much for your guidance, support, patience, and time. It was a great honor to participate and contribute. Looking forward for more too!
