### PR TITLE
GH-3374: Fix scan for BF propagation

### LINKED ISSUE #3374: NPE when @ConditionalOnBean is present alongside with the @MessagingGateway
For example:

5.2.x and above

**Describe the bug**

In Spring Boot application we declare like this:
```
	@ConditionalOnBean(name = "foo")
	@MessagingGateway
	public interface ConditionalGateway {

		void testGateway(Object payload);

	}
```
and get an excpetion at start up:
```
	at com.example.demo.DemoApplication.main(DemoApplication.java:13) [classes/:na]
Caused by: java.lang.IllegalStateException: Error processing condition on com.example.demo.DemoApplication$ConditionalGateway
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:90) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:71) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isConditionMatch(ClassPathScanningCandidateComponentProvider.java:513) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:496) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:430) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 22 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.containsBean(OnBeanCondition.java:288) ~[spring-boot-autoconfigure-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:197) ~[spring-boot-autoconfigure-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:119) ~[spring-boot-autoconfigure-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.3.3.RELEASE.jar:2.3.3.RELEASE]
```

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/3374

An internal `ClassPathScanningCandidateComponentProvider` instance in the `IntegrationComponentScanRegistrar`
does not propagate a provided `registry`.

* Implement `getRegistry()` on the internal `ClassPathScanningCandidateComponentProvider` to propagate
a provided into the `registerBeanDefinitions()` a `BeanDefinitionRegistry`
* Add `@Conditional` on some scanned `@MessagingGateway` in the `EnableIntegrationTests`

**Cherry-pick to 5.3.x & 5.2.x**

### CODE REVIEW

File: spring-integration-core/src/main/java/org/springframework/integration/config/IntegrationComponentScanRegistrar.java [hunk 1]
```diff
@@ -150,7 +154,7 @@ private void filter(BeanDefinitionRegistry registry, Map<String, Object> compone
 	}
 
 	protected Collection<String> getBasePackages(AnnotationMetadata importingClassMetadata,
-			@SuppressWarnings("unused") BeanDefinitionRegistry registry) {
+			BeanDefinitionRegistry registry) {
```
Comment (garyrussell) [inline spring-integration-core/src/main/java/org/springframework/integration/config/IntegrationComponentScanRegistrar.java:157]: ? It is still unused (this was added to suppress a Sonar issue).

**Review by garyrussell — CHANGES_REQUESTED** [review]

File: spring-integration-core/src/main/java/org/springframework/integration/config/IntegrationComponentScanRegistrar.java (hunk 1 above)
Comment (artembilan) [reply spring-integration-core/src/main/java/org/springframework/integration/config/IntegrationComponentScanRegistrar.java:157]: Hm. I'm always super suspicious for any code which IDEA shows as  redundant.
I'm not sure what the problem sees Sonar, but that's fully OK to override the method and don't use all the provided params.
🤷

Comment (garyrussell) [reply spring-integration-core/src/main/java/org/springframework/integration/config/IntegrationComponentScanRegistrar.java:157]: Sounds like a bug in IDEA to me; the variable is clearly not used here; whether the super method uses it is irrelevant.

Comment (artembilan) [reply spring-integration-core/src/main/java/org/springframework/integration/config/IntegrationComponentScanRegistrar.java:157]:
```suggestion
			@SuppressWarnings("unused") BeanDefinitionRegistry registry) {
```

**Comment by garyrussell** [comment]
And cherry-picked with no conflicts.
