### PR TITLE
GH-10163: Fallback to default errorChannel in RabbitStreamMessageHandler

### LINKED ISSUE #10163: RabbitMQ Streams Client Errors Getting Lost
**In what version(s) of Spring Integration are you seeing this issue?**
5.3.1.RELEASE

**Describe the bug**
If the RabbitMQ Stream client throws an error, it seems that the RabbitStreamMessageHandler is catching them but not properly sending it down an errorChannel.

**To Reproduce**
We have a [sample project](https://github.com/metron2/streams-demo/blob/d44dbd5087e005cd738d5628d113f52ed9c60ad5/src/main/java/com/example/demo/DemoWriterConfiguration.java#L64) that resembles our code in production. You can see we create the RabbitStreamMessageHandler as [per the docs](https://docs.spring.io/spring-integration/reference/amqp/rmq-streams.html#rmq-stream-outbound-channel-adapter). Unfortunately, this results in a `null` value for the `sendFailureChannel` and `sendFailureChannelName`. 

By contrast if we manually set a `sendFailureChannelName` to `"errorChannel"`, we can see the errors thrown by the client. 

```java
@Bean
public IntegrationFlow demoOutboundChannelAdapter(
        RabbitStreamTemplate myStreamTemplate, MessageChannel outboundChannel) {
    return IntegrationFlow.from(outboundChannel)
            .handle(RabbitStream.outboundStreamAdapter(myStreamTemplate)
                .sync(true)
                .sendFailureChannel("errorChannel"))
            .get();
}
```

The error were specifically encountering (and is represented in the sample repo) is when a message is too large, it exceeds the `frame_max` size. The stack trace we see looks like this (truncated):

```
[demo] [   scheduling-1] o.s.integration.handler.LoggingHandler   : java.lang.IllegalArgumentException: Message too big to fit in one frame: 5243004
        at com.rabbitmq.stream.impl.Client.checkMessageFitsInFrame(Client.java:479)
        at com.rabbitmq.stream.impl.ProducerUtils$MessageAccumulatorHelper.entity(ProducerUtils.java:301)
        at com.rabbitmq.stream.impl.DynamicBatchMessageAccumulator.add(DynamicBatchMessageAccumulator.java:133)
        at com.rabbitmq.stream.impl.StreamProducer.doSend(StreamProducer.java:402)
        at com.rabbitmq.stream.impl.StreamProducer.send(StreamProducer.java:385)
        at com.rabbitmq.stream.impl.SuperStreamProducer.send(SuperStreamProducer.java:120)
        at org.springframework.rabbit.stream.producer.RabbitStreamTemplate.observeSend(RabbitStreamTemplate.java:276)
...
```

**Expected behavior**
If this is expected behaviour, then it should be documented, but I doubt this is the case. I would hope the expected behaviour is to send to the default `"errorChannel"`. Perhaps setting that as the default value is a reasonable fix.

**Sample**
https://github.com/metron2/streams-demo

### PR DESCRIPTION
**Pull request by rrileyca**
Fixes: #10163

If RabbitStreamMessageHandler was used in async mode, error messages were dropped unless a sendFailureChannel or sendFailureChannelName were provided. This adds the "errorChannel" name as a fallback.

### CODE REVIEW

**Comment by rrileyca** [comment]
@artembilan Third time is the charm. I hope I have cleaned up everything now up to Spring's standards!

File: spring-integration-kafka/src/test/java/org/springframework/integration/kafka/outbound/KafkaProducerMessageHandlerTests.java [hunk 1]
```diff
@@ -543,7 +544,9 @@ void testConsumeAndProduceTransaction() throws Exception {
 		KafkaMessageDrivenChannelAdapter inbound = new KafkaMessageDrivenChannelAdapter<>(container);
 		DirectChannel channel = new DirectChannel();
 		inbound.setOutputChannel(channel);
+		DirectChannel sendFailureChannel = new DirectChannel();
```
Comment (artembilan) [inline spring-integration-kafka/src/test/java/org/springframework/integration/kafka/outbound/KafkaProducerMessageHandlerTests.java]: Why do you introduce his variable if it is out of verification part?

**Review by artembilan — CHANGES_REQUESTED** [review]

**Comment by artembilan** [comment]
The PR looks really good .
Pay attention how PR description has matched from your first commit message .
Plus now with that `Fixed:` it will close issue on merge.

> up to Spring's standards

it is not about standards, but reasoning and convenience for all of us. The code style is also for easy to read. So, yeah, we can call it “standard”, but that came after years of cooperation with the community and back & forth attempts . Therefore now we can even call it “the way” 😉

File: spring-integration-kafka/src/test/java/org/springframework/integration/kafka/outbound/KafkaProducerMessageHandlerTests.java (hunk 1 above)
Comment (rrileyca) [reply spring-integration-kafka/src/test/java/org/springframework/integration/kafka/outbound/KafkaProducerMessageHandlerTests.java]: I did this because without it, the call to `getChannelResolver()` would throw an error because the `beanFactory` is null. Instead of creating a BeanFactory *and* a message channel, I thought it would be harmless to just create a channel and set it in order to circumvent the error.

**Comment by rrileyca** [comment]
> Therefore now we can even call it “the way” 😉

Thank you for showing me the way then! This was fun. I hope to contribute more in the future - this time, with clean PRs ;)

File: spring-integration-kafka/src/test/java/org/springframework/integration/kafka/outbound/KafkaProducerMessageHandlerTests.java (hunk 1 above)
Comment (artembilan) [reply spring-integration-kafka/src/test/java/org/springframework/integration/kafka/outbound/KafkaProducerMessageHandlerTests.java]: Oh, I see! So, we probably just can use `new NullChannel()` in that setter and no any extra local variables.

Comment (rrileyca) [reply spring-integration-kafka/src/test/java/org/springframework/integration/kafka/outbound/KafkaProducerMessageHandlerTests.java]: I had forgotten about the NullChannel. Good idea. Fixed.

**Comment by artembilan** [comment]
There is one more problem , @rrileyca : 

> Signed-off-by: rrileyca <rriley.ca@gmail.com>

That has to be your legal name if you are OK with legal obligations according to DCO.
If you are not, then we cannot accept contributions from you.

I took a liberty to modify your final commit message on merge, but I hope you’ll fix you Git client to populate a proper name.

Thank you again !

**Comment by rrileyca** [comment]
I had made a non-global config in the previous repo, which I since deleted and recreated. Sorry about that. My legal name is Ryan Riley, as per the `@author` annotations.

Thank you!

**Comment by artembilan** [comment]
I think I did it right: https://github.com/spring-projects/spring-integration/commit/f4670e58be5fe238fb9441897b917613bb78c1eb

**Comment by rrileyca** [comment]
> I think I did it right: [f4670e5](https://github.com/spring-projects/spring-integration/commit/f4670e58be5fe238fb9441897b917613bb78c1eb)

You did!
