### PR TITLE
Fix MQTTv5 reconnection race condition

### LINKED ISSUE #10697: Revise MQTT Message Handlers logic around recconnection
The current logic is like this:

```
	@Override
	protected void publish(String topic, Object mqttMessage, Message<?> message) {
		Assert.isInstanceOf(MqttMessage.class, mqttMessage, "The 'mqttMessage' must be an instance of 'MqttMessage'");
		long completionTimeout = getCompletionTimeout();
		try {
			if (!this.mqttClient.isConnected()) {
				this.lock.lock();
				try {
					if (!this.mqttClient.isConnected()) {
						this.mqttClient.connect(this.connectionOptions).waitForCompletion(completionTimeout);
					}
				}
				finally {
					this.lock.unlock();
				}
			}
```

Even if we double check `this.mqttClient.isConnected()`, the `this.mqttClient.connect()` still may lead to the race condition with other `mqttClient` consumers and fail with:
```
Caused by: org.eclipse.paho.mqttv5.common.MqttException: Connect already in progress	
	at org.eclipse.paho.mqttv5.client.MqttAsyncClient.connect(MqttAsyncClient.java:734)	
	at org.eclipse.paho.mqttv5.client.MqttAsyncClient.connect(MqttAsyncClient.java:715)	
	at org.springframework.integration.mqtt.outbound.Mqttv5PahoMessageHandler.publish(Mqttv5PahoMessageHandler.java:249)
```

That does not mean that we are good to `publish` already, but at least means that we can check for `this.mqttClient.isConnected()` is a `while` loop in the `catch` block.
According to the Paho library:
```
		if (comms.isConnected()) {
			throw ExceptionHelper.createMqttException(MqttClientException.REASON_CODE_CLIENT_CONNECTED);
		}
		if (comms.isConnecting()) {
			throw new MqttException(MqttClientException.REASON_CODE_CONNECT_IN_PROGRESS);
		}
```
It looks like we need to check for both errors in the `catch` block.

### PR DESCRIPTION
**Pull request by cppwfs**
Fixes: #10697

Address race condition in `Mqttv5PahoMessageHandler` when multiple threads attempt to connect simultaneously.

Changes:
- Add `RetryTemplate` with configurable retry count for connection attempts
- Implement `MqttExceptionMatcher` to handle specific MQTT error codes
- Add `setRetryConnectionCount` method to configure retry behavior
- Create test suite validating retry logic

The retry mechanism specifically handles `REASON_CODE_CONNECT_IN_PROGRESS` and `REASON_CODE_CLIENT_CONNECTED` errors, allowing the client to recover gracefully when connection establishment is already in progress. Default retry count is set to 5 with 100ms delay between attempts.

### CODE REVIEW

**Comment by artembilan** [comment]
Good. I’ll take a look into your idea in the morning. Meanwhile , please , check this where we give a retry option already: https://docs.spring.io/spring-integration/reference/handler-advice.html

**Comment by cppwfs** [comment]
Good point.   I thought about allowing the user set the retry policy but thought it was overkill.   But after your comment above, I reconsidered and added that capability.

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5ReconnectionRaceConditionTests.java [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+import static org.mockito.BDDMockito.given;
+import static org.mockito.BDDMockito.willAnswer;
+import static org.mockito.BDDMockito.willDoNothing;
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.times;
+import static org.mockito.Mockito.verify;
+
+/**
+ * Tests for race condition handling in {@link Mqttv5PahoMessageHandler}
+ * when multiple threads attempt to connect simultaneously
```
Comment (artembilan) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5ReconnectionRaceConditionTests.java]: It is indeed a race condition, but not necessary between different threads connecting.
The client might be disconnected by the broker just after `isConnected()`.
So, let's consider to not confuse with this Javadoc, but just talk about a connection problem!

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5ReconnectionRaceConditionTests.java [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+ *
+ * @since 7.1
+ */
+public class Mqttv5ReconnectionRaceConditionTests {
+
+	@Test
+	public void testConnectAfterSingleInProgress() throws Exception {
+		IMqttAsyncClient mockClient = mock(IMqttAsyncClient.class);
+		IMqttToken mockConnectToken = mock(IMqttToken.class);
+		IMqttToken mockPublishToken = mock(IMqttToken.class);
```
Comment (artembilan) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5ReconnectionRaceConditionTests.java]: We can use just simple `mock()` to simplify our code.

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5ReconnectionRaceConditionTests.java [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+		willDoNothing().given(mockPublishToken).waitForCompletion(anyLong());
+		given(mockPublishToken.getMessageId()).willReturn(1);
+
+		Mqttv5PahoMessageHandler handler = createHandler(mockClient);
+
+		Message<String> message = MessageBuilder.withPayload("test").build();
+
+		handler.handleMessage(message);
+		verify(mockClient, times(1)).connect(any(MqttConnectionOptions.class));
+		verify(mockClient, times(1)).publish(anyString(), any(MqttMessage.class), any(), any());
```
Comment (artembilan) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5ReconnectionRaceConditionTests.java]: It is `times(1)` by default?
Why go explicitly?

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5ReconnectionRaceConditionTests.java [hunk 4]
```diff
@@ -0,0 +1,161 @@
...
+
+		// Simulate the race condition scenario:
+		// 1. Initially disconnected
+		// 2. After first connect attempt (which throws), another thread completes the connection
+		// 3. Subsequent isConnected() calls return true
+		willAnswer(invocation -> connectionCompleted.get()).given(mockClient).isConnected();
+
+		willAnswer(invocation -> {
+			int attempt = connectAttempts.incrementAndGet();
+			if (attempt == 1) {
```
Comment (artembilan) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5ReconnectionRaceConditionTests.java]: Why do we need to extract into a local variable?

File: spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/outbound/Mqttv5PahoMessageHandler.java [hunk 5]
```diff
@@ -245,24 +247,40 @@ protected void publish(String topic, Object mqttMessage, Message<?> message) {
...
+								int reasonCode = ex.getReasonCode();
+								if (reasonCode == MqttClientException.REASON_CODE_CONNECT_IN_PROGRESS) {
+										Thread.sleep(100);
+								}
+								else if (reasonCode != MqttClientException.REASON_CODE_CLIENT_CONNECTED) {
+									throw ex;
+								}
+							}
+						}
+
```
Comment (artembilan) [inline spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/outbound/Mqttv5PahoMessageHandler.java]: Nit-pick, but for clear code this empty line is redundant.

**Review by artembilan — CHANGES_REQUESTED** [review]
This is great!
Thank you!

**Review by artembilan — APPROVED** [review]
Thank you!
Will merge when build is green
