### PR TITLE
GH-3955: Mqttv5PahoMessageDrivenChannelAdapter only unsubscribe when cleanStart

### LINKED ISSUE #3955: MQTTv5: Mqttv5PahoMessageDrivenChannelAdapter unsubscribes from topics even when cleanStart/cleanSession is false
**In what version(s) of Spring Integration are you seeing this issue?**

sprint-boot 2.7.5
spring-integration-mqtt 5.5.15
org.eclipse.paho.mqttv5.client 1.2.5

**Describe the bug**
Mqttv5PahoMessageDrivenChannelAdapter unsubscribes from all topics, even if cleanStart/cleanSession is set to false, thus not receiving offline messages after restart. Similar behaviour to https://jira.spring.io/browse/INT-3900 but for MQTT v5.

**To Reproduce**
- Create a Mqttv5PahoMessageDrivenChannelAdapter with setCleanStart(false) and setSessionExpiryInterval with e.g. 5000secs
- Subscribe to some topics
- Stop application
- On the broker you will see that it unsubscribes from all topics

**Expected behavior**

The Mqttv5PahoMessageDrivenChannelAdapter does not unsubscribe in inStop.
Mqttv5PahoMessageDrivenChannelAdapter.java:

```
protected void doStop() {
		this.topicLock.lock();
		String[] topics = getTopic();
		try {
			if (this.mqttClient != null && this.mqttClient.isConnected()) {
				this.mqttClient.unsubscribe(topics).waitForCompletion(getCompletionTimeout());

				if (getClientManager() == null) {
					this.mqttClient.disconnect().waitForCompletion(getCompletionTimeout());
				}
			}
		}
		catch (MqttException ex) {
			logger.error(ex, () -> "Error unsubscribing from " + Arrays.toString(topics));
		}
		finally {
			this.topicLock.unlock();
		}
	}
```

MqttPahoMessageDrivenChannelAdapter (v3) does a check:
```
	protected synchronized void doStop() {
		try {
			if (this.consumerStopAction.equals(ConsumerStopAction.UNSUBSCRIBE_ALWAYS)
					|| (this.consumerStopAction.equals(ConsumerStopAction.UNSUBSCRIBE_CLEAN)
					&& this.cleanSession)) {

				this.client.unsubscribe(getTopic());
			}
		}
```

Proposed fix:
```
    @Override
    protected void doStop() {
        this.topicLock.lock();
        String[] topics = getTopic();
        try {
            if (this.mqttClient != null && this.mqttClient.isConnected()) {
                /** FIX */
                if (connectionOptions.isCleanStart()) {
                    this.mqttClient.unsubscribe(topics).waitForCompletion(getCompletionTimeout());
                }
                /** FIX */
                this.mqttClient.disconnect().waitForCompletion(getCompletionTimeout());
            }
        }
        catch (MqttException ex) {
            logger.error(ex, () -> "Error unsubscribing from " + Arrays.toString(topics));
        }
        finally {
            this.topicLock.unlock();
        }
    }
```

### PR DESCRIPTION
**Pull request by mths1**
GH-3955: Mqttv5PahoMessageDrivenChannelAdapter only unsubscribe when cleanStart

Fixes spring-projects/spring-integration#3955

* add check to doStop that avoids unsubscribe when cleanStart is false.
* add testcase

### CODE REVIEW

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+		verify(client).unsubscribe(any(String[].class));
+	}
+
+	private void verifyNotUnsubscribe(IMqttAsyncClient client) throws Exception {
+		verify(client).connect(any(MqttConnectionOptions.class));
+		verify(client).subscribe(any(MqttSubscription[].class),any(), any(), any(IMqttMessageListener[].class), any());
+		verify(client, never()).unsubscribe(any(String[].class));
+	}
+
+	private Mqttv5PahoMessageDrivenChannelAdapter buildAdapterIn(final IMqttAsyncClient client, Boolean cleanStart) throws MqttException {
```
Comment (artembilan) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java:62]: Why that cannot be a primitive `boolean`?

Why I'm OK with this method (which has to be `static`, BTW, and in the end of test class), I don't see a reason in other two.

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+	@Test
+	public void testStopNotClean() throws Exception {
+		final IMqttAsyncClient client = mock(IMqttAsyncClient.class);
+		Mqttv5PahoMessageDrivenChannelAdapter adapter = buildAdapterIn(client, false);
+
+		adapter.start();
+		adapter.connectComplete(false, null);
+		adapter.stop();
+		verifyNotUnsubscribe(client);
+	}
```
Comment (artembilan) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java:105]: Blank line after each class member.

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+import static org.mockito.Mockito.never;
+import static org.mockito.Mockito.verify;
+
+/**
+ * @author Gary Russell
+ * @author Artem Bilan
+ * @author Artem Vozhdayenko
+ * @author Matthias Thoma
+ *
+ * @since 6.0.1
```
Comment (artembilan) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java:45]: `5.5.16` - we are going to back-port the fix.

**Review by artembilan — CHANGES_REQUESTED** [review]

**Comment by artembilan** [comment]
Also see Checkstyle errors:
```
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java:27:1: 'org.springframework.beans.factory.BeanFactory' should be separated from previous imports. [ImportOrder]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java:52:71: ',' is not followed by whitespace. [WhitespaceAfter]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java:58:71: ',' is not followed by whitespace. [WhitespaceAfter]
Error: eckstyle] [ERROR] /home/runner/work/spring-integration/spring-integration/spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java:74:69: ',' is not followed by whitespace. [WhitespaceAfter]
```

You can verify your change locally using Gradle command: `gradlew clean :spring-integration-mqtt:check`

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java (hunk 1 above)
Comment (mths1) [reply spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java:62]: There is no particular reason. I took that code from MqttAdapterTests (the v3 version) and didn't want to change it too much to keep those two similar.

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java (hunk 3 above)
Comment (mths1) [reply spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java:45]: ok

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java (hunk 2 above)
Comment (mths1) [reply spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/Mqttv5AdapterTests.java]: changed

**Comment by artembilan** [comment]
... and back-ported to `5.5.x` as https://github.com/spring-projects/spring-integration/commit/36e4fe1fb56f0d6a2ac2a55cc7c4afc6aef2cba0 after fixing conflicts.

@mths1 ,

thank you for contribution; looking forward for more!
