### PR TITLE
GH-10574: Rely on `WebServiceTemplate.defaultUri`

### LINKED ISSUE #10574: `spring-integration-ws` WS DSL requires setting URI when WebServiceTemplate already has default URI set
**In what version(s) of Spring Integration are you seeing this issue?**

7.0.0.RC2

**Describe the bug**

`Ws.marshallingOutboundGateway` will not start without specifying the `.uri()` in the DSL, even though the supplied `WebServiceTemplate` has a `defaultUri` set

**To Reproduce**

1. Create WebService Marshalling Outbound Gateway, specifying only the WebServiceTemplate
```java
return f -> f.handle(WS.marshallingOutboundGateway(webServiceTemplate);
```

Application fails to start, indicating the Ws.marshallingOutboundGateway requires the URI to be set

**Expected behavior**

`Ws.marshallingOutboundGateway()` should be able to infer the uri from the supplied `WebServiceTemplate` if the defaultUri has been set.

### PR DESCRIPTION
**Pull request by artembilan**
Fixes: https://github.com/spring-projects/spring-integration/issues/10574

* Change the logic of the `AbstractWebServiceOutboundGateway` to take into account a `WebServiceTemplate.defaultUri` option as an alternative to the explicit `uri` or `destinationProvider`
* Expose `WebServiceTemplate`-based ctor in the `SimpleWebServiceOutboundGateway` (The `MarshallingWebServiceOutboundGateway` already has one)
* Adjust tests and XML parser to cover a new logic
* Mention the change in docs

### CODE REVIEW

File: spring-integration-ws/src/main/java/org/springframework/integration/ws/outbound/AbstractWebServiceOutboundGateway.java [hunk 1]
```diff
@@ -106,11 +107,16 @@ public AbstractWebServiceOutboundGateway(DestinationProvider destinationProvider
...
 		// we always call WebServiceTemplate methods with an explicit URI argument,
-		// but in case the WebServiceTemplate is accessed directly we'll set this:
+		// but in case the WebServiceTemplate is accessed directly, we'll set this:
 		this.webServiceTemplate.setDestinationProvider(destinationProvider);
 		this.uri = null;
 	}
 
+	public AbstractWebServiceOutboundGateway(WebServiceTemplate webServiceTemplate) {
+		doSetWebServiceTemplate(webServiceTemplate);
+		this.destinationProvider = null;
```
Comment (cppwfs) [inline spring-integration-ws/src/main/java/org/springframework/integration/ws/outbound/AbstractWebServiceOutboundGateway.java:117]: Curious as to why we are setting the `destinationProvider` to `null`, since it is default is `null`.

File: src/reference/antora/modules/ROOT/pages/ws.adoc [hunk 2]
```diff
@@ -40,6 +40,7 @@ To invoke a web service when you send a message to a channel, you have two optio
 The former accepts either a `String` or `javax.xml.transform.Source` as the message payload.
 The latter supports any implementation of the `Marshaller` and `Unmarshaller` interfaces.
 Both require a Spring Web Services `DestinationProvider`, to determine the URI of the web service to be called.
+Or explicit uri directly, or via `WebServiceTemplate.defaultUri` (since version 7.1).
```
Comment (cppwfs) [inline src/reference/antora/modules/ROOT/pages/ws.adoc]: I think we can replace the period with another comma:   For example
Both require a Spring Web Services `DestinationProvider` to determine the URI of the web service to be called, or an explicit URI can be provided directly or via `WebServiceTemplate.defaultUri` (since version 7.1).

**Review by cppwfs — APPROVED** [review]
This is a great addition.   Just my annoying questions and nitpicks!

File: spring-integration-ws/src/main/java/org/springframework/integration/ws/outbound/AbstractWebServiceOutboundGateway.java (hunk 1 above)
Comment (artembilan) [reply spring-integration-ws/src/main/java/org/springframework/integration/ws/outbound/AbstractWebServiceOutboundGateway.java:117]: Because it is `final`.

Comment (cppwfs) [reply spring-integration-ws/src/main/java/org/springframework/integration/ws/outbound/AbstractWebServiceOutboundGateway.java:117]: DOh!   Yep!

**Review by cppwfs — APPROVED** [review]
Thank you for the update!

LGTM!
