### PR TITLE
GH-3454: From MQTT conversion error - to error ch

### LINKED ISSUE #3454: Paho loses connection if the message converter returns null
**In what version(s) of Spring Integration are you seeing this issue?**

5.2.8.RELEASE

**Describe the bug**

The paho mqtt client loses the connection if a custom converter returns null. In my case the application pairs each incoming message with some mandatory information. If the information are absent for any reason we return null in order to stop the spi message delivery.

#### MqttPahoMessageDrivenChannelAdapter
```java
@Override
public void messageArrived(String topic, MqttMessage mqttMessage) {
	Message<?> message = this.getConverter().toMessage(topic, mqttMessage);
	try {
		sendMessage(message);
	}
	catch (RuntimeException e) {
		logger.error("Unhandled exception for " + message.toString(), e);
		throw e;
	}
}
```

#### MessageProducerSupport
```java
protected void sendMessage(Message<?> messageArg) {
		Message<?> message = messageArg;
		if (message == null) {
			throw new MessagingException("cannot send a null message");
		}
              
                ...
}
```

**To Reproduce**

1. Implement a PahoMessageConverter
2. Make the `toMessage` method return null
3. Send a message and observe the client getting disconnected

**Expected behavior**

The client should drop the message entirely if the converter returns null.

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/3454

The message converter may return null when we try to covert from the
MQTT message.
The thrown exception may also reset the client connect.

* Fix `MqttPahoMessageDrivenChannelAdapter` to catch any conversion errors
(including `null` result) and try to send an `ErrorMessage` with that info
into the provided `errorChannel`.
Otherwise re-throw it as as

**Cherry-pick to `5.4.x` & `5.3.x`**

### CODE REVIEW

**Comment by artembilan** [comment]
I will do back-port to `5.2.x` after review and merging: it does not support `MessageBuilder` contract yet.

Thanks

File: spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java [hunk 1]
```diff
@@ -399,19 +401,52 @@ public synchronized void connectionLost(Throwable cause) {
...
 		}
-		catch (RuntimeException ex) {
-			logger.error(ex, () -> "Unhandled exception for " + message.toString());
-			throw ex;
+		catch (Exception ex) {
+			conversionError = ex;
+		}
+
+		if (builder == null && conversionError == null) {
+			conversionError = new IllegalStateException("'MqttMessageConverter' produced a null for message");
```
Comment (garyrussell) [inline spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java:432]:
```suggestion
			conversionError = new IllegalStateException("'MqttMessageConverter' returned 'null'");
```

File: spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java [hunk 2]
```diff
@@ -399,19 +401,52 @@ public synchronized void connectionLost(Throwable cause) {
...
+			if (!sendErrorMessageIfNecessary(message, conversionError)) {
+				MessageConversionException conversionException;
+				if (conversionError instanceof MessageConversionException) {
+					conversionException = (MessageConversionException) conversionError;
+				}
+				else {
+					conversionException = new MessageConversionException(message, "Failed to convert from MQTT Message",
+							conversionError);
+				}
+				throw conversionException;
```
Comment (garyrussell) [inline spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java:446]: Should we still throw here? Or just log as ERROR?

File: src/reference/asciidoc/mqtt.adoc [hunk 3]
```diff
@@ -164,6 +164,9 @@ StaticMessageHeaderAccessor.acknowledgment(someMessage).acknowledge();
 ----
 ====
 
+Starting with version `5.2.11`, when message converter throws an exception or returns `null` from the `MqttMessage` conversion, the `MqttPahoMessageDrivenChannelAdapter` sends an `ErrorMessage` into the provided `errorChannel`.
+Re-throws this conversion error otherwise into an MQTT client callback.
```
Comment (garyrussell) [inline src/reference/asciidoc/mqtt.adoc:168]:
```suggestion
Starting with version `5.2.11`, when the message converter throws an exception or returns `null` from the `MqttMessage` conversion, the `MqttPahoMessageDrivenChannelAdapter` sends an `ErrorMessage` into the `errorChannel`, if provided.
Re-throws this conversion error otherwise into an MQTT client callback.
```

Also see my comment in the code about re-throwing.

**Review by garyrussell — CHANGES_REQUESTED** [review]

File: spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java (hunk 2 above)
Comment (artembilan) [reply spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java:446]: Well, I tried to make it consistent with what we have so far in the `MessageProducerSupport.sendMessage()`:
```
try {
	this.messagingTemplate.send(getRequiredOutputChannel(), message);
}
catch (RuntimeException ex) {
	if (!sendErrorMessageIfNecessary(message, ex)) {
		throw ex;
	}
}
```

We probably may consider some general `ErrorHandler` strategy. However it looks like we have it already for this kind of channel adapters via an `ErrorHandlingTaskExecutor` impl. Nevertheless I don't see that we have some way to inject it into the `MqttAsyncClient`...

Probably the matter for a separate issue and discussion over there...

Comment (garyrussell) [reply spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java:446]: Right, but the problem here is that throwing an exception causes the client to close. Conversion exceptions are generally fatal anyway (no point in retrying) since a redelivery will fail again.

However, it would be a behavior change so we'd probably have to add a flag.

Or, we can just leave it as you have it; up to you.

Comment (artembilan) [reply spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java:446]: Well, we have a flag - `errorChannel` and no exceptions are thrown back to the client!
I would stay with this behavior for a while: probably everybody is going to be happy to swallow and process those wrong messages in the error flow instead of just silent (log) drop to satisfy the client connection stability.

**Comment by artembilan** [comment]
@garyrussell ,

let me know if anything else you'd like to see fixed with this PR!
Thanks

**Review by garyrussell — APPROVED** [review]

**Comment by garyrussell** [comment]
Cherry-picked to 5.4.x and to 5.3.x after resolving conflicts.

Ready for 5.2.x backport.

**Comment by artembilan** [comment]
Back-ported to `5.2.x` as https://github.com/spring-projects/spring-integration/commit/71d41757cd9655b41e334926968d247cf9e267e1
