### PR TITLE
GH-3888: Fix NPE in the `RedisLockRegistry.destroy()`

### LINKED ISSUE #3888: NullPointerException when RedisLockRegistry is destroyed
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.14

**Describe the bug**

During spring shutdown, a Null Pointer exception is thrown when the RedisLockRegistry is destroyed (because the redisMessageListenerContainer attribute is null).

**To Reproduce**

Run the following application. When shutting down, this warning message is logged :

`2022-09-19 18:13:53.065  WARN 2260 --- [ionShutdownHook] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'redisLockRegistry': java.lang.IllegalStateException: java.lang.NullPointerException `

**Expected behavior**

It seems possible that there is no instance of redisMessageListenerContainer. We may check that the listener exists before calling destroy on it.

**Sample**

[demo.zip](https://github.com/spring-projects/spring-integration/files/9606043/demo.zip)

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.3</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
			<exclusions>
				<exclusion>
					<groupId>io.lettuce</groupId>
					<artifactId>lettuce-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
			<version>3.8.0</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

```
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.data.redis.RedisProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.data.redis.connection.RedisStandaloneConfiguration;
import org.springframework.data.redis.connection.jedis.JedisConnectionFactory;
import org.springframework.integration.redis.util.RedisLockRegistry;

@SpringBootApplication
public class DemoApplication {

	private String LOCK_NAME = "lock";

	@Bean
	public RedisLockRegistry redisLockRegistry(RedisProperties redisProperties) {
		RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration(
				"localhost", 6379);
		JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory(redisStandaloneConfiguration);
		jedisConnectionFactory.afterPropertiesSet();
		return new RedisLockRegistry(jedisConnectionFactory, LOCK_NAME);
	}

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}
```

### PR DESCRIPTION
**Pull request by artembilan**
Fixed https://github.com/spring-projects/spring-integration/issues/3888

When `RedisLockType.SPIN_LOCK` (default), the `RedisLockRegistry.destroy()` causes an NPE on the `redisMessageListenerContainer` since pub-sub is not used in a busy-spin mode

* Check for `redisMessageListenerContainer` before calling its `destroy()`

**Cherry-pick to 5.5.x**

### CODE REVIEW

File: spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisLockRegistry.java [hunk 1]
```diff
@@ -245,11 +245,13 @@ public void destroy() {
...
 		}
-		try {
-			this.redisMessageListenerContainer.destroy();
-		}
-		catch (Exception ex) {
-			throw new IllegalStateException(ex);
+		if (this.redisMessageListenerContainer != null) {
+			try {
+				this.redisMessageListenerContainer.destroy();
+			}
```
Comment (garyrussell) [inline spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisLockRegistry.java:251]: Shouldnt we also set it to null here?

**Review by garyrussell — COMMENTED** [review]
Just one comment/question.

**Comment by garyrussell** [comment]
...and cherry-picked, resolving conflicts in tests.
