### PR TITLE
GH-3946: Revise Router channelKeyFallback option

### LINKED ISSUE #3946: Spring DSL defaultOutputToParentFlow does not behave as described
**In what version(s) of Spring Integration are you seeing this issue?**
5.1.4.RELEASE

**Describe the bug**

When creating an IntegrationFlow bean using `IntegrationFlows.from(CHANNEL)`, in the `route(Function<S, T> router, Consumer<RouterSpec<T, MethodInvokingRouter>> routerConfigurer)` method, when configuring the router mappings, the method `defaultOutputToParentFlow()` does not what the documentation says it does.

Example:

Given this Integration Flow definition:
```
 @Bean
    public IntegrationFlow orderIntegrationFlow() {
        return IntegrationFlows.from(CHANNEL)
                .<Order, OrderType>route(Order::getType,
                        r -> r.channelMapping(OrderType.DINE_IN, DineInOrderFlow.CHANNEL)
                                .channelMapping(OrderType.ONLINE, OnlineOrderFlow.CHANNEL)
                                .defaultOutputToParentFlow()
                )
                .log("It only reaches here if Order::getType is null.")
                .get();
    }

```

The log will only get printed if `Order::getType` is null. This is contrary to the javadoc which says that:

```
Make a default output mapping of the router to the parent flow. Use the next, after router, parent flow MessageChannel as a AbstractMessageRouter.setDefaultOutputChannel(MessageChannel) of this router.
```

**To Reproduce**

Create a Spring project in Java 11, using Spring 5.3.20 and Spring Integration 5.1.4.RELEASE .

Create an IntegrationFlow bean using the default `IntegrationFlows.from()` method:

```
    public static final String CHANNEL = "orderInputChannel";

    @Bean(name = CHANNEL)
    public MessageChannel getChannel() {
        DirectChannel dc = new DirectChannel();
        dc.setComponentName(CHANNEL);
        return dc;
    }


    @Bean
    public IntegrationFlow orderIntegrationFlow() {
        return IntegrationFlows.from(CHANNEL)
                .<Order, OrderType>route(Order::getType,
                        r -> r.channelMapping(OrderType.DINE_IN, DineInOrderFlow.CHANNEL)
                                .channelMapping(OrderType.ONLINE, OnlineOrderFlow.CHANNEL)
                                .defaultOutputToParentFlow()
                )
                .log("It only reaches here if Order::getType is null.")
                .get();
    }
```

Create a class called Order:

```
public class Order {

    private OrderType orderType;
    public OrderType getType() {
        return orderType;
    }

    public void setType(OrderType orderType) {
        this.orderType = orderType;
    }

}
```

And an enum called OrderType:

```
public enum OrderType {
    DINE_IN,
    ONLINE,
    TAKEAWAY;
}
```

And with everything setup correctly, send a message to CHANNEL of an `Order` with `OrderType.TAKEAWAY`.

**Expected behavior**

The `log()` at the end of the `orderIntegrationFlow` will be called because the `defaultOutputToParent` reached a default state.

** Actual behavior **

An Exception is thrown where TAKEAWAY is not found to be a proper CHANNEL name defined in the Spring Context. Only if Order::getOrderType returns null, then the `log()` function is called.

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/3946

The `AbstractMappingMessageRouter` has both `resolutionRequired` and `channelKeyFallback` as `true` by default.
End-users expects them to back off when they set a `defaultOutputChannel`. They really want something similar to Java `switch` statement

* Change the logic in the `AbstractMappingMessageRouter` to reset `channelKeyFallback` to `false` when `defaultOutputChannel` to avoid attempts to resolve channel from name, but rather fallback to `defaultOutputChannel` as it states from th mentioned Java `switch` statement experience
* Deprecate `RouterSpec.noChannelKeyFallback()` in favor of newly introduced `channelKeyFallback(boolean)`
* Call `channelKeyFallback(false)` from an overloaded `defaultOutputToParentFlow()` to reflect the mentioned expected behavior in Java DSL as well.
* Respectively, deprecate `KotlinRouterSpec.noChannelKeyFallback()` wrapper in favor of newly introduced `channelKeyFallback(channelKeyFallback: Boolean)`
* Remove redundant already `noChannelKeyFallback()` option in the `NoFallbackAllowedTests`
* Document the change and new behavior

### CODE REVIEW

File: spring-integration-core/src/main/java/org/springframework/integration/dsl/RouterSpec.java [hunk 1]
```diff
@@ -205,6 +221,20 @@ public RouterSpec<K, R> subFlowMapping(K key, IntegrationFlow subFlow) {
 		return _this();
 	}
 
+	/**
+	 * Make a default output mapping of the router to the parent flow.
+	 * Use the next, after router, parent flow {@link MessageChannel} as a
+	 * {@link AbstractMessageRouter#setDefaultOutputChannel(MessageChannel)} of this router.
+	 * This option also disables {@link AbstractMappingMessageRouter#setChannelKeyFallback(boolean)},
+	 * if not called explicitly, to skip an attempt to resolve channel name.
```
Comment (garyrussell) [inline spring-integration-core/src/main/java/org/springframework/integration/dsl/RouterSpec.java:229]:
```suggestion
	 * if not called explicitly afterwards, to skip an attempt to resolve the channel name.
```

File: spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java [hunk 2]
```diff
@@ -124,15 +128,70 @@ public void setResolutionRequired(boolean resolutionRequired) {
...
 	public void setChannelKeyFallback(boolean channelKeyFallback) {
 		this.channelKeyFallback = channelKeyFallback;
+		this.channelKeyFallbackSetExplicitly = true;
+	}
+
+	/**
+	 * Set the default channel where Messages should be sent if channel resolution
+	 * fails to return any channels.
+	 * It also sets {@link #channelKeyFallback} to {@code false} to avoid
+	 * an attempt to resolve a channel from its key, but instead send message
```
Comment (garyrussell) [inline spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java:147]:
```suggestion
	 * an attempt to resolve a channel from its key, but instead send the message
```

File: spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java [hunk 3]
```diff
@@ -124,15 +128,70 @@ public void setResolutionRequired(boolean resolutionRequired) {
...
+	 * directly to this channel.
+	 * If {@link #channelKeyFallback} is set explicitly to {@code true},
+	 * the further logic depend on a {@link #resolutionRequired} options
```
Comment (garyrussell) [inline spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java:150]:
```suggestion
	 * the logic depends on the {@link #resolutionRequired} option
```

File: spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java [hunk 4]
```diff
@@ -124,15 +128,70 @@ public void setResolutionRequired(boolean resolutionRequired) {
...
+	 * ({@code true} by default), and therefore a fallback to
+	 * this default output channel may never happen.
+	 * The configuration where default output channel is present and
+	 * {@link #resolutionRequired} and {@link #resolutionRequired} are set to {@code true}
+	 * is rejected since it leads to ambiguity.
```
Comment (garyrussell) [inline spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java:155]:
```suggestion
	 * The configuration where a default output channel is present and
	 * {@link #setResolutionRequired resolutionRequired} and 
	 * {@link #setChannelKeyFallback channelKeyFallback} are set to {@code true}
	 * is rejected since it leads to ambiguity.
```

File: spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java [hunk 5]
```diff
@@ -124,15 +128,70 @@ public void setResolutionRequired(boolean resolutionRequired) {
...
```
Comment (garyrussell) [inline spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java:182]: Same changes here.

File: spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java [hunk 6]
```diff
@@ -189,15 +248,14 @@ public Collection<String> getDynamicChannelNames() {
...
-	protected abstract List<Object> getChannelKeys(Message<?> message);
-
+	@Override
+	protected void onInit() {
+		super.onInit();
+		Assert.state(!this.channelKeyFallback || !this.resolutionRequired || !this.defaultOutputChannelSet,
+				"The 'defaultOutputChannel' cannot be reached " +
+						"when both 'channelKeyFallback' & 'resolutionRequired' are set to true. " +
+						"See their javadocs for more information.");
+	}
```
Comment (garyrussell) [inline spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java:258]: I don't think we can enforce this; what if both are true and channel resolution is successful.

File: src/reference/asciidoc/router.adoc [hunk 7]
```diff
@@ -349,7 +349,10 @@ If set, this attribute provides a reference to the channel where messages should
 If no default output channel is provided, the router throws an exception.
 If you would like to silently drop those messages instead, set the default output channel attribute value to `nullChannel`.
 +
-NOTE: A message is sent only to the `default-output-channel` if `resolution-required` is `false` and the channel is not resolved.
+NOTE: Starting with version 6.0, setting a default output channel also resets `channelKeyFallback` option to `false`.
+So, no attempts to resolve a channel from name, but rather fallback to this default output channel - similar to Java `switch` statement.
```
Comment (garyrussell) [inline src/reference/asciidoc/router.adoc:353]:
```suggestion
NOTE: Starting with version 6.0, setting a default output channel also resets the `channelKeyFallback` option to `false`.
So, no attempts will be made to resolve a channel from its name, but rather fallback to this default output channel - similar to a Java `switch` statement.
```

File: src/reference/asciidoc/router.adoc [hunk 8]
```diff
@@ -349,7 +349,10 @@ If set, this attribute provides a reference to the channel where messages should
...
+If `channelKeyFallback` is set to `true` explicitly, the further logic depends on the `resolutionRequired` option: the message can reach a `defaultOutputChannel` only if `resolutionRequired` is `false`.
+Therefore, a configuration where `defaultOutputChannel` is provided and both `channelKeyFallback` & `resolutionRequired` are set to `true` is rejected by the `AbstractMappingMessageRouter` initialization phase.
```
Comment (garyrussell) [inline src/reference/asciidoc/router.adoc:355]: We can't enforce this. See comment above.

File: src/reference/asciidoc/whats-new.adoc [hunk 9]
```diff
@@ -110,6 +110,11 @@ For convenience, the XML and Java DSL for Scatter-Gather, based on the `Recipien
 
 See <<./scatter-gather.adoc#scatter-gather,Scatter-Gather>> for more information.
 
+Another convenient behaviour change has been done for an `AbstractMappingMessageRouter`.
+Now setting a `defaultOutputChannel` also resets a `channelKeyFallback` to `false`, so no attempts to resolve channel from its key, but immediate fallback to `defaultOutputChannel`.
```
Comment (garyrussell) [inline src/reference/asciidoc/whats-new.adoc:114]:
```suggestion
Another convenient behavior change has been made to the `AbstractMappingMessageRouter`.
Now, setting a `defaultOutputChannel` also resets the `channelKeyFallback` property to `false`, so no attempts will be made to resolve a channel from its key, but the logic immediately falls back to sending the mesage to the `defaultOutputChannel`.
```

**Review by garyrussell — CHANGES_REQUESTED** [review]
Mostly docs, but one important.

File: spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java (hunk 6 above)
Comment (artembilan) [reply spring-integration-core/src/main/java/org/springframework/integration/router/AbstractMappingMessageRouter.java:258]: Correct. And what is the reason to have a `defaultOutputChannel` then?
You simply can set `channelKeyFallback = true`, but `resolutionRequired = false`.
So, if resolution is OK, we go there, if it is not we fallback to a default channel.

We probably can improve docs for this as well.

**Comment by artembilan** [comment]
I don't think we need to say anything else.
This sentence in docs covers everything:

> If `channelKeyFallback` is set to `true` explicitly, the further logic depends on the `resolutionRequired` option: the message to non-resolved channel from key can reach a `defaultOutputChannel` only if `resolutionRequired` is `false`.

**Comment by artembilan** [comment]
My point  with this change is that end-users expects a behavior a-la Java `swtich` expression.
So, they don't consider a resolution from key.
Kinda let's make a default behavior as obvious as possible 😄

**Review by garyrussell — APPROVED** [review]
