### PR TITLE
INT-3923: Fix MQTT Reconnect Logic

### LINKED ISSUE #2046: MQTT client attemps to reconnect indefinitely
I have tried to connect two MQTT clients with the same ID to the same broker without knowing that the clientID must be unique. In this situation both clients tries indefinitely to connect to the broker (normal behaviour) but when you stop one of them, the other one goes on attemping to reconnect with the debug message "MqttPahoMessageDrivenChannelAdapter : Attempting reconnect" forever. The only way to solve the problem is restart the application.

I don't know if this is a bug or the expected behaviour. These are the logs for the error of the instance that remains attemping to reconnect.

```
2017-02-02 14:50:39.487 DEBUG 27039 --- [nio-8081-exec-2] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@696f298c
2017-02-02 14:50:45.384 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:45.384 DEBUG 27039 --- [mtfsParserInput] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'taskScheduler'
2017-02-02 14:50:45.385 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:45.432 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:45.450 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:45.450 DEBUG 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:45.565 ERROR 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Error connecting or subscribing to [mtfs-connector/tap]

org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 common frames omitted

2017-02-02 14:50:45.566 ERROR 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Exception while connecting and subscribing

org.eclipse.paho.client.mqttv3.MqttException: Client is currently disconnecting
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:455)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:632)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:601)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:608)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.connectAndSubscribe(MqttPahoMessageDrivenChannelAdapter.java:246)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.access$300(MqttPahoMessageDrivenChannelAdapter.java:47)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter$1.run(MqttPahoMessageDrivenChannelAdapter.java:287)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2017-02-02 14:50:45.568 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:45.569 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:45.700 ERROR 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Error connecting or subscribing to [mtfs-connector/tap]

org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 common frames omitted

2017-02-02 14:50:45.701 ERROR 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Exception while connecting and subscribing

org.eclipse.paho.client.mqttv3.MqttException: Client is disconnected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:451)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:632)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:601)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:608)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.connectAndSubscribe(MqttPahoMessageDrivenChannelAdapter.java:246)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.access$300(MqttPahoMessageDrivenChannelAdapter.java:47)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter$1.run(MqttPahoMessageDrivenChannelAdapter.java:287)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

.
.
.

2017-02-02 14:50:46.462 DEBUG 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.548 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:46.549 DEBUG 27039 --- [ask-scheduler-8] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.549 ERROR 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Error connecting or subscribing to [mtfs-connector/tap]

org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 common frames omitted

2017-02-02 14:50:46.549 ERROR 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Exception while connecting and subscribing

org.eclipse.paho.client.mqttv3.MqttException: Client is disconnected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:451)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:632)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:601)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:608)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.connectAndSubscribe(MqttPahoMessageDrivenChannelAdapter.java:246)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.access$300(MqttPahoMessageDrivenChannelAdapter.java:47)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter$1.run(MqttPahoMessageDrivenChannelAdapter.java:287)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2017-02-02 14:50:46.621 DEBUG 27039 --- [ask-scheduler-8] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:46.637 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:46.639 DEBUG 27039 --- [ask-scheduler-5] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.699 DEBUG 27039 --- [ask-scheduler-5] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:46.721 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:46.721 DEBUG 27039 --- [ask-scheduler-4] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.823 DEBUG 27039 --- [ask-scheduler-4] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:46.824 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:46.825 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.909 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:49.490 DEBUG 27039 --- [nio-8081-exec-3] o.s.b.w.f.OrderedRequestContextFilter    : Bound request context to thread: org.apache.catalina.connector.RequestFacade@696f298c
2017-02-02 14:50:49.490 DEBUG 27039 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing GET request for [/health]
2017-02-02 14:50:49.490 DEBUG 27039 --- [nio-8081-exec-3] o.s.b.a.e.mvc.EndpointHandlerMapping     : Looking up handler method for path /health
2017-02-02 14:50:49.491 DEBUG 27039 --- [nio-8081-exec-3] o.s.b.a.e.mvc.EndpointHandlerMapping     : Returning handler method [public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(java.security.Principal)]
2017-02-02 14:50:49.491 DEBUG 27039 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : Last-Modified value for [/health] is: -1
2017-02-02 14:50:49.519 DEBUG 27039 --- [nio-8081-exec-3] m.m.a.RequestResponseBodyMethodProcessor : Written [UP {discoveryComposite=UP {discoveryClient=UP {services=[MtfsParser, consul]}}, diskSpace=UP {total=486303457280, free=411104645120, threshold=10485760}, refreshScope=UP {}, hystrix=UP {}, consul=UP {services={MtfsParser=[], consul=[]}, advertiseAddress=127.0.0.1, datacenter=mtfs-test, domain=consul., nodeName=os-lin-jra, bindAddress=0.0.0.0, clientAddress=127.0.0.1}}] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@7530090a]
2017-02-02 14:50:49.519 DEBUG 27039 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2017-02-02 14:50:49.519 DEBUG 27039 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : Successfully completed request
2017-02-02 14:50:49.520 DEBUG 27039 --- [nio-8081-exec-3] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@696f298c
2017-02-02 14:50:55.566 DEBUG 27039 --- [ask-scheduler-6] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:55.701 DEBUG 27039 --- [ask-scheduler-7] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:55.933 DEBUG 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.016 DEBUG 27039 --- [ask-scheduler-8] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.115 DEBUG 27039 --- [ask-scheduler-5] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.206 DEBUG 27039 --- [ask-scheduler-4] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.342 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.462 DEBUG 27039 --- [sk-scheduler-10] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.550 DEBUG 27039 --- [ask-scheduler-9] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
```

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INT-3923

Fixes: #2046

Previously, when connection is lost, the inbound adapter attempted to reconnect on
a schedule with a fixed delay.

If a connection was again lost, while the schedule is still running, we can end up
with another scheduled task running.

This is benign aside from the DEBUG log noise because the scheduled task tests the
connection before reconnecting.

However, if the `recoveryInterval` is short, it could consume CPU.

Change the reconnect to be a one-time scheduled task and reschedule if it fails to
reconnect.

Synchronize all access to the `connected` field.

Add a test case with a short recovery interval, before this fix, we see many logs
`Attempting reconnect`.

__cherry-pick to 4.3.x - but the `schedule()` lambda will have to be changed to a `Runnable`__

### CODE REVIEW

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/MqttAdapterTests.java [hunk 1]
```diff
@@ -369,6 +377,34 @@ public void testCustomExpressions() {
...
+			}
+			i.callRealMethod();
+			return null;
+		}).given(logger).debug("Attempting reconnect");
+		ThreadPoolTaskScheduler taskScheduler = new ThreadPoolTaskScheduler();
+		taskScheduler.initialize();
+		adapter.setTaskScheduler(taskScheduler);
+		adapter.start();
+		adapter.connectionLost(new RuntimeException("initial"));
+		Thread.sleep(1000);
```
Comment (artembilan) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/MqttAdapterTests.java]: Works for me even without this.
Am I missing anything?
Can't we switch to the `CountDownLatch` in the `willAnswer` impl? 

Aren't we pursuing the goal to be sure that reconnect called several times in case of `connectionLost()`?

Or we can `spy()` on the `TaskScheduler.schedule()` for the same `latch` reason

**Review by artembilan — CHANGES_REQUESTED** [review]
Only some concern in the test-case

File: spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/MqttAdapterTests.java (hunk 1 above)
Comment (garyrussell) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/MqttAdapterTests.java]: No; the test is to make sure the reconnect is not performed more than twice. We need to wait a little bit to ensure that.

If you revert the src/main code, this test fails because the log is called many times.

Of course, now that it's no longer called on a schedule we can probably drop the test altogether.

Comment (artembilan) [inline spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/MqttAdapterTests.java]: OK. Let it be.
One more sec won't hurt.
Merging...

**Review by artembilan — APPROVED** [review]

**Comment by artembilan** [comment]
... and cherry-picked as https://github.com/spring-projects/spring-integration/commit/4c68e22d87e2ce2d5fea9202d03a9a378b3f4773
