### PR TITLE
Fixed issue where the Java DSL will always create NIO connection factories regardless of which type you specified.

### LINKED ISSUE #2346: Spring Integration IP Java DSL creates wrong connection factories
In version 5.0 the Java DSL will always create NIO connection factories regardless of which type you specified.

### PR DESCRIPTION
**Pull request by TYsewyn**
Fixes #2346

### CODE REVIEW

File: spring-integration-ip/src/main/java/org/springframework/integration/ip/dsl/Tcp.java [hunk 1]
```diff
@@ -37,7 +38,7 @@
 	 * Boolean indicating the connection factory should not use NIO
 	 * (default).
 	 */
-	public static final boolean NET = true;
+	public static final boolean NET = false;
```
Comment (artembilan) [inline spring-integration-ip/src/main/java/org/springframework/integration/ip/dsl/Tcp.java]: Uh! That's nasty.

I suggest to deprecate both these constants altogether because they are not used in the Framework at all.

And use just simply `true/false` in those factories.

**Review by artembilan — CHANGES_REQUESTED** [review]
