### PR TITLE
GH-3696: DeserializationEx support for KafkaMS

### LINKED ISSUE #3696: Support ErrorHandlingDeserializer in KafkaMessageSource
**Expected Behavior**

Similar logic to the listener container - send deserialization exceptions to the error channel.

**Current Behavior**

User has to manually move past the bad record by setting the offset.

**Context**

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/3696

* Add an internal logic into `KafkaMessageSource` to react properly for the `ErrorHandlingDeserializer` configuration and re-throw `DeserializationException`

### CODE REVIEW

**Comment by artembilan** [comment]
In general just copy/pasted the logic from the `KafkaMessageListenerContainer`.
Not sure what could be done better though...

Thanks

File: spring-integration-kafka/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageSource.java [hunk 1]
```diff
@@ -257,11 +271,68 @@ public Collection<TopicPartition> getAssignedPartitions() {
...
+		this.checkNullKeyForExceptions =
+				this.consumerProperties.isCheckDeserExWhenKeyNull() ||
+						checkDeserializer(findDeserializerClass(props, kafkaConsumerProperties, false));
+		this.checkNullValueForExceptions =
+				this.consumerProperties.isCheckDeserExWhenValueNull() ||
+						checkDeserializer(findDeserializerClass(props, kafkaConsumerProperties, true));
+	}
+
+	@Nullable
+	private Object findDeserializerClass(Map<String, Object> props, Properties consumerOverrides, boolean isValue) {
```
Comment (garyrussell) [inline spring-integration-kafka/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageSource.java:296]: I will move most of the duplicated code to `SK.ErrorHandlingUtils`; then you can use it from there.

Comment (artembilan) [reply spring-integration-kafka/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageSource.java:296]: Sounds good!

Comment (garyrussell) [reply spring-integration-kafka/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageSource.java:296]: https://github.com/spring-projects/spring-kafka/pull/2756

File: spring-integration-kafka/src/test/java/org/springframework/integration/kafka/inbound/MessageSourceIntegrationTests.java [hunk 2]
```diff
@@ -122,4 +138,66 @@ public void onPartitionsAssigned(Collection<TopicPartition> partitions) {
 		template.destroy();
 	}
 
+	@Test
+	void deserializationErrorIsThrownFromSource() throws Exception {
+		Map<String, Object> consumerProps = KafkaTestUtils.consumerProps(brokers, "testErrorChannelSource", "false");
+		consumerProps.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
```
Comment (garyrussell) [inline spring-integration-kafka/src/test/java/org/springframework/integration/kafka/inbound/MessageSourceIntegrationTests.java:144]: FYI, this is now the default in KTU.

File: spring-integration-kafka/src/test/java/org/springframework/integration/kafka/inbound/MessageSourceIntegrationTests.java [hunk 3]
```diff
@@ -122,4 +138,66 @@ public void onPartitionsAssigned(Collection<TopicPartition> partitions) {
...
+		source.start();
+
+		Map<String, Object> producerProps = KafkaTestUtils.producerProps(brokers);
+		DefaultKafkaProducerFactory<Object, Object> producerFactory = new DefaultKafkaProducerFactory<>(producerProps);
+		KafkaTemplate<Object, Object> template = new KafkaTemplate<>(producerFactory);
+
+		String testData = "test data";
+		template.send(TOPIC2, testData);
+
+		source.receive(); // Trigger Kafka Consumer creation and poll()
```
Comment (garyrussell) [inline spring-integration-kafka/src/test/java/org/springframework/integration/kafka/inbound/MessageSourceIntegrationTests.java:180]: I am not entirely sure, but the record might be returned by this initial poll.

It would be safer to remove this and move the following assertion into the `untilAsserted() -> {...}` block.

**Review by garyrussell — CHANGES_REQUESTED** [review]

**Review by garyrussell — APPROVED** [review]
