### PR TITLE
fix: re-new connection in PostgresChannelMessageTableSubscriber

### LINKED ISSUE #9061: PostgresChannelMessageTableSubscriber not properly handling Database Failover
**In what version(s) of Spring Integration are you seeing this issue?**

6.x

**Describe the bug**

When the database is doing a failover the `PostgresChannelMessageTableSubscriber` doesn't notice and will never receive new notifications.
For example on AWS RDS instance with multi-AZ standby, when performing a failover the IP address for the DNS does change. But `PostgresChannelMessageTableSubscriber` never re-establishes a connection, nor has some other measurement in place to validate that the connection is still valid.

**To Reproduce**

Perform a DB failover. After this no more messages will be processed.

**Expected behavior**

Eventually the `PostgresChannelMessageTableSubscriber` obtains a new connection after failover, and message processing will work again.

**Sample**

Sorry, not being able to provide a complete sample, as this involves infrastructure 🤷‍♂️

### PR DESCRIPTION
**Pull request by joshiste**
PostgresChannelMessageTableSubscriber currently never renews the connection. This causes problems on DB failover. With this change the connection is renewed when notifications are not received for a certain time.

fixes #9061

### CODE REVIEW

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriber.java [hunk 1]
```diff
@@ -278,6 +285,19 @@ private static String getKey(Object input) {
 		return input == null ? null : UUIDConverter.getUUID(input).toString();
 	}
 
+	/**
+	 * Set the timeout for the notification polling.
+	 * If for the specified duration no notificiation are received the underlying connection is closed and re-established.
+	 * Setting a value of {@code Duration.ZERO} will disable the timeout and wait forever.
+	 * This might cause problems in DB failover scenarios.
+	 *
```
Comment (artembilan) [inline spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriber.java:293]: No blank lines in the method Javadocs.
Please, move this new setter to the setters sections, which usually is after constructor.
Also add your name to the `@author` list.

**Review by artembilan — CHANGES_REQUESTED** [review]
I wonder if we can simulate the reconnection somehow in the unit test.
See `PostgresChannelMessageTableSubscriberTests`.

Also note: the version `6.0.x` is out of Open Source Support.
So, we accept the fix and back-port it down to `6.1.x` only.

Thanks

**Comment by joshiste** [comment]
> I wonder if we can simulate the reconnection somehow in the unit test.
See PostgresChannelMessageTableSubscriberTests.

I've added a test that verifies for reconnection after certain time without notifications

File: spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriberTests.java [hunk 2]
```diff
@@ -261,6 +263,26 @@ void testRetryOnErrorDuringDispatch(boolean transactionsEnabled) throws Interrup
 		assertThat(payloads).containsExactly("1");
 	}
 
+	@Test
+	public void testRenewConnection() throws Exception {
+		CountDownLatch latch = new CountDownLatch(2);
+		List<Object> payloads = new ArrayList<>();
+		CountDownLatch connectionLatch = new CountDownLatch(2);
+		connectionSupplier.onGetConnection = connectionLatch::countDown;
```
Comment (artembilan) [inline spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriberTests.java:271]: We need to set it to `null` in the end of test.
There is just no guarantee in test method executions order.

File: spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriberTests.java [hunk 3]
```diff
@@ -300,4 +322,19 @@ public JdbcChannelMessageStore jdbcChannelMessageStore(DataSource dataSource) {
 
 	}
 
+	private static class ConnectionSupplier implements PgConnectionSupplier {
+		Runnable onGetConnection;
```
Comment (artembilan) [inline spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriberTests.java:326]: Every member in the class must be surrounded with blank lines.
Including the last method in the class. 

Run `gradlew :spring-integration-jdbc:check`  locally.

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriber.java [hunk 4]
```diff
@@ -116,6 +120,18 @@ public void setTaskExecutor(AsyncTaskExecutor taskExecutor) {
 		this.taskExecutor = taskExecutor;
 	}
 
+	/**
+	 * Set the timeout for the notification polling.
+	 * If for the specified duration no notificiation are received the underlying connection is closed and re-established.
+	 * Setting a value of {@code Duration.ZERO} will disable the timeout and wait forever.
+	 * This might cause problems in DB failover scenarios.
+	 * @param notificationTimeout the timeout for the notification polling.
```
Comment (artembilan) [inline spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriber.java:128]: `@since 6.1.8`

**Review by artembilan — CHANGES_REQUESTED** [review]

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriber.java (hunk 4 above)
Comment (joshiste) [reply spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriber.java:128]: fixed

File: spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriberTests.java (hunk 2 above)
Comment (joshiste) [reply spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriberTests.java:271]: It is initialized in the `BeforeEach` there is no need in unsetting,  as each test will have a new instance.

File: spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriberTests.java (hunk 3 above)
Comment (joshiste) [reply spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/channel/PostgresChannelMessageTableSubscriberTests.java:327]: fixed

**Review by artembilan — CHANGES_REQUESTED** [review]
Something is off with a new test:
```
PostgresChannelMessageTableSubscriberTests > testRenewConnection() FAILED
    org.opentest4j.AssertionFailedError at PostgresChannelMessageTableSubscriberTests.java:282
```

**Comment by artembilan** [comment]
... and cherry-picked to `6.2.x` & `6.1.x`.

Thank you for contribution; looking forward for more!

**Comment by joshiste** [comment]
What is the schedule for the next release?

**Comment by artembilan** [comment]
April, 16
