### PR TITLE
GH-8778: Fix KafkaMessageSource deadlock

### LINKED ISSUE #8778: Deadlock in KafkaMessageSource - between isRunning and doReceive
For more context: https://github.com/spring-cloud/spring-cloud-stream/issues/2675

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/8778

The `KafkaMessageSource.doReceive()` have a lock around its whole body. That includes the `pollRecord()` which can be blocked on the `KafkaConsumer.poll()`. This way the rest of lifecycle management callbacks can be blocked until `KafkaConsumer.poll()` returns.

* Rework lifecycle management flags to `AtomicBoolean` since there is not too much work in their respective callbacks
* Decrease a locking block in the `doReceive()` just to consumer setup part. Leave `pollRecord()` outside of the lock
* Add `this.consumer.wakeup()` into `stopConsumer()` to break a `poll()` cycle and return immediately for the next `close()` call

**Cherry-pick to `6.1.x` & `6.0.x`**

### CODE REVIEW

**Comment by artembilan** [comment]
CC @sobychacko

**Comment by sobychacko** [comment]
LGTM, @artembilan

File: spring-integration-kafka/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageSource.java [hunk 1]
```diff
@@ -409,104 +410,72 @@ private boolean maxPollStringGtr1(Object maxPoll) {
...
-		this.lock.lock();
-		try {
-			stopConsumer();
-			this.running = false;
-			this.stopped = true;
-		}
-		finally {
-			this.lock.unlock();
-		}
+		stopConsumer();
```
Comment (garyrussell) [inline spring-integration-kafka/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageSource.java:424]: `if (this.running.compareAndSet(true, false)) {...}`

File: spring-integration-kafka/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageSource.java [hunk 2]
```diff
@@ -409,104 +410,72 @@ private boolean maxPollStringGtr1(Object maxPoll) {
...
 	public void start() {
-		this.lock.lock();
-		try {
-			this.running = true;
-			this.stopped = false;
-		}
-		finally {
-			this.lock.unlock();
-		}
+		this.running.set(true);
```
Comment (garyrussell) [inline spring-integration-kafka/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageSource.java:418]: `if (this.running.compareAndSet(false, true)) {...}`

**Review by garyrussell — CHANGES_REQUESTED** [review]
This won't cherry-pick because of the `ReentrantLock`.

**Comment by artembilan** [comment]
> This won't cherry-pick because of the `ReentrantLock`.

I have back-ported today such a fix: https://github.com/spring-projects/spring-integration/commit/991d29eb153898e8e572938f7e24ee81248523e3
Exactly for a simple review and back-port process of this PR.

**Review by garyrussell — APPROVED** [review]

**Comment by garyrussell** [comment]
...and cherry-picked.
