### PR TITLE
GH-6375: Harmonize package structures

### LINKED ISSUE #6375: Standardize Package Structure across Modules [INT-2389]
**[Gunnar Hillert](https://jira.spring.io/secure/ViewProfile.jspa?name=hillert)** opened **[INT-2389](https://jira.spring.io/browse/INT-2389?redirect=false)** and commented

Going through the package structures, it seems that SI Modules generally follow a defined package structure, e.g. org.springframework.integration.<module_name>.config etc.

It seems, though, we have certain deviations e.g. putting stuff into the module root package versus having a "core" package.

This might also be something to think about, when we create a common guideline/documentation for writing custom components.

Some common package structures:

* "inbound"
* "outbound"
* "core" (for common)
* "support" if even core needs something
* "mapping"
* "config"
* The "root" package should contain only exceptions and possibly base interfaces

---

**Affects:** 2.1 RC2

### PR DESCRIPTION
**Pull request by artembilan**
Fixes: https://github.com/spring-projects/spring-integration/issues/6375

* Move respective classes to the `inbound`, `outbound` or `support` packages to make the whole picture for the API more concise and clean

The firs commit is for `stream` module

### CODE REVIEW

**Comment by artembilan** [comment]
This is not too hard task moving classes from one package to another with respective `@Deprecated` routine, but this might be hard to review.
Just because the code has been copied/pasted and looks like a new now.
So, let me know if you still would like this PRs approach or that wouldbe OK if I just do the stuff and push to `main`.

I have changed the comment in the issue to checkboxes, so we may even divide those packages between us.

I decided to go with a  `@Deprecated` instead of plain move for easier migration even if we are in a major right now.

Any feedback welcome!

Thanks

**Comment by artembilan** [comment]
I think that's enough for now.
It might be easier to review commit by commit, since each of them belongs to the specific module.
However, it is still hard because the number of changes getting bigger.

Please, let me know if this is OK with you and I'll continue to nail the issue.

Thanks

**Comment by artembilan** [comment]
So, the PR is getting bigger and bigger.
Just because it is not only move to new packages to come to harmony in the end, but this also causes an entropy to preserve old classes with deprecation mark.
I also move test classes into new packages as well.
Therefore, I'm not sure what you'd like to review here.
Just let me know how you feel about this overhaul!

I'm going to push more since I got this spare time and it makes sense for the current major we are about to finish.

Thank you for your time since I feel guilty to waste it on this huge PR review 😄

File: spring-integration-stream/src/main/java/org/springframework/integration/stream/event/StreamClosedEvent.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+package org.springframework.integration.stream.event;
+
+import org.springframework.integration.events.IntegrationEvent;
+
+/**
+ * Application event published when EOF is detected on a stream.
+ *
+ * @author Gary Russell
+ *
```
Comment (cppwfs) [inline spring-integration-stream/src/main/java/org/springframework/integration/stream/event/StreamClosedEvent.java:25]: Nitpick.  
I'm not sure we need it, but do you think we need an @author tag?  Or is the commit history satisfactory for documentation?

File: spring-integration-ws/src/main/java/org/springframework/integration/ws/MarshallingWebServiceOutboundGateway.java [hunk 2]
```diff
@@ -103,59 +99,10 @@ public MarshallingWebServiceOutboundGateway(@Nullable String uri, WebServiceTemp
...
-
-		PassThroughRequestMessageCallback(@Nullable WebServiceMessageCallback requestCallback, Message<?> requestMessage) {
-			super(requestCallback, requestMessage);
-		}
-
-		@Override
-		public void doWithMessageInternal(WebServiceMessage message, Object payload) throws IOException {
-		}
 
+		super(destinationProvider, webServiceTemplate);
```
Comment (cppwfs) [inline spring-integration-ws/src/main/java/org/springframework/integration/ws/MarshallingWebServiceOutboundGateway.java:105]: I'm debating...    Do we need tests on the constructors in the deprecated classes?    
My hyper nitpicky voice in the back of my head said we should at least mention it.

File: spring-integration-jmx/src/main/resources/org/springframework/integration/jmx/config/spring-integration-jmx.xsd [hunk 3]
```diff
@@ -301,7 +301,7 @@
 						</xsd:documentation>
```
Comment (cppwfs) [inline spring-integration-jmx/src/main/resources/org/springframework/integration/jmx/config/spring-integration-jmx.xsd:301]: Line 131 needs to be updated to the new package name.

File: spring-integration-file/src/main/java/org/springframework/integration/file/FileReadingMessageSource.java [hunk 4]
```diff
@@ -94,48 +63,16 @@
...
-
-	private Predicate<Path> watchDirPredicate = path -> true;
+@Deprecated(forRemoval = true, since = "7.0")
+public class FileReadingMessageSource extends org.springframework.integration.file.inbound.FileReadingMessageSource {
 
 	/**
 	 * Create a FileReadingMessageSource with a naturally ordered queue of unbounded capacity.
 	 */
 	public FileReadingMessageSource() {
-		this(null);
```
Comment (cppwfs) [inline spring-integration-file/src/main/java/org/springframework/integration/file/FileReadingMessageSource.java:138]: Wouldn't this be super(null)?

**Review by cppwfs — CHANGES_REQUESTED** [review]
What a PR!   😆 

Great work!   Breaking up the inbound and outbound classes into their own packages makes perfect sense. 

Just my usual nitpicks.

**Comment by mrpiggi** [comment]
> This is not too hard task moving classes from one package to another with respective `@Deprecated` routine, but this might be hard to review. Just because the code has been copied/pasted and looks like a new now. So, let me know if you still would like this PRs approach or that wouldbe OK if I just do the stuff and push to `main`.
> I decided to go with a `@Deprecated` instead of plain move for easier migration even if we are in a major right now.

Looks like a very tedious task. Just be aware, that if you proceed in this manner, you will actually lose the git history of all the moved files. If you want to retain the history you would have to do the moving in one commit and re-introduce the now deprecated classes as new ones in a subsequent commit. Not sure, if it's worth the effort but I just wanted to mention it.

**Comment by cppwfs** [comment]
Thank you for your comment it is very much appreciated.
Even after the removal of the deprecated versions from the main branch, the original classes are still be accessible in all previous tags and branches with their complete history. However, it is an additional step to do a blame.

File: spring-integration-stream/src/main/java/org/springframework/integration/stream/event/StreamClosedEvent.java (hunk 1 above)
Comment (artembilan) [reply spring-integration-stream/src/main/java/org/springframework/integration/stream/event/StreamClosedEvent.java:25]: This was just a class move.
I add (and request) `@author` tag when a reasonable change is made to the class.

File: spring-integration-ws/src/main/java/org/springframework/integration/ws/MarshallingWebServiceOutboundGateway.java (hunk 2 above)
Comment (artembilan) [reply spring-integration-ws/src/main/java/org/springframework/integration/ws/MarshallingWebServiceOutboundGateway.java:105]: I could not find yet a decent reason in my guts to cover deprecated classes with tests.
I treat deprecated API from my dependencies as obsolete, therefore it might be broken.
So, I switch to a new API as soon as possible.

But I may consider to have coverage for deprecated as well if you give me more arguments.
Plus, I have you as extra help to do that supporting work 😄

File: spring-integration-file/src/main/java/org/springframework/integration/file/FileReadingMessageSource.java (hunk 4 above)
Comment (artembilan) [reply spring-integration-file/src/main/java/org/springframework/integration/file/FileReadingMessageSource.java:138]: Why?
If we don't specify `super()`, that `super()` is compiled-in.
And that `super()` does exactly what you are asking.

**Comment by artembilan** [comment]
> do the moving in one commit and re-introduce the now deprecated classes as new ones

That is great idea!
I don't think I'll revert anything what I have done so far, but I'll try to follow your recommendations for two remaining modules.

Thank you for review!

> in all previous tags and branches with their complete history

Yeah... Unfortunately, after removing deprecated classes in the next version we won't have their mentioning anywhere to follow the history.

File: spring-integration-ws/src/main/java/org/springframework/integration/ws/MarshallingWebServiceOutboundGateway.java (hunk 2 above)
Comment (cppwfs) [reply spring-integration-ws/src/main/java/org/springframework/integration/ws/MarshallingWebServiceOutboundGateway.java:105]: In the code review, I really didn't see an appreciable benefit to adding them.  
I think the rule is, if you add anything outside `super(...)` then a test would be required.
But as with anything, it was worth mentioning.

**Review by cppwfs — APPROVED** [review]
LGTM 
Do you want me to merge and we start a new PR for the rest of the work, or continue with this PR?

**Comment by artembilan** [comment]
>  or continue with this PR?

There are just only two modules left.
And I'm at the moment on JDBC.
So, I don't see a reason for a new PR.

Just state tuned!
I'll finish the work for this task today.
Thank you!

**Comment by cppwfs** [comment]
Sounds great!

**Comment by artembilan** [comment]
Just pushed two commits for JDBC module.
I think that is exactly what you mean about preserving history and blame.

**Comment by artembilan** [comment]
OK. I think this is all whatever has needed to be done for the issue.

File: spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/package-info.java [hunk 5]
```diff
@@ -1,5 +0,0 @@
-/**
- * Base package for TCP Support.
- */
-@org.jspecify.annotations.NullMarked
```
Comment (cppwfs) [inline spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/package-info.java:4]: Should this be readded for the deprecated classes?

File: src/reference/antora/modules/ROOT/pages/whats-new.adoc [hunk 6]
```diff
@@ -57,6 +57,13 @@ The `RetryStateGenerator` abstraction and its `SpelExpressionRetryStateGenerator
 
 See xref:handler-advice/classes.adoc#retry-advice[Retry Advice] for more information.
 
+All the modules now follow the standard package structure.
+The inbound and outbound components are declared in the `inbound` and `outbound` packages, respectively.
+The `MessageChannel` implementations in the `channel` package.
+Most of the modules have followed this rule from day first.
```
Comment (cppwfs) [inline src/reference/antora/modules/ROOT/pages/whats-new.adoc]: Update to say "from the first day"

**Review by cppwfs — CHANGES_REQUESTED** [review]
Looks good.
Just a question and a quick doc fix and its ready to go.

**Review by cppwfs — APPROVED** [review]
LGTM.   

Want me to merge?
