### PR TITLE
GH-3980: Fix concurrent initialization in DefaultSftpSessionFactory

### LINKED ISSUE #3980: Concurrent threads might use uninitialised SFTP client
**In what version(s) of Spring Integration are you seeing this issue?**

spring-integration-sftp 6.0.1

**Describe the bug**

If SFTP client is not yet initialised and two threads simultaneously try to use SFTP client, one of them may fail.

`DefaultSftpSessionFactory::initClientSession` calls `DefaultSftpSessionFactory::initClient` which initialises the client.
Client initialisation is done only by the first thread.
The second thread skips initialisation and may use uninitialised/partially initialised client.
It causes exception:
```java
Caused by: java.lang.IllegalStateException: failed to create SFTP Session
	at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:291)
	at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:67)
	at org.springframework.integration.file.remote.session.CachingSessionFactory$1.createForPool(CachingSessionFactory.java:85)
	at org.springframework.integration.file.remote.session.CachingSessionFactory$1.createForPool(CachingSessionFactory.java:82)
	at org.springframework.integration.util.SimplePool.doGetItem(SimplePool.java:206)
	at org.springframework.integration.util.SimplePool.getItem(SimplePool.java:187)
	... 20 common frames omitted
Caused by: java.lang.IllegalStateException: SshClient not started. Please call start() method before connecting to a server
	at org.apache.sshd.client.SshClient.doConnect(SshClient.java:626)
	at org.apache.sshd.client.SshClient.doConnect(SshClient.java:615)
	at org.apache.sshd.client.SshClient.connect(SshClient.java:546)
	at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:199)
	at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:188)
	at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.initClientSession(DefaultSftpSessionFactory.java:314)
	at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:281)
	... 25 common frames omitted
```

**To Reproduce**

After application startup when SFTP client is not yet initialised make two SFTP requests simultaneously

**Expected behavior**

All threads must wait for client initialisation. 
Uninitialised/partially initialised client should never be used.

### PR DESCRIPTION
**Pull request by kdebski85**
fixes: https://github.com/spring-projects/spring-integration/issues/3980

Fix concurrent initialization in DefaultSftpSessionFactory

### CODE REVIEW

**Comment by artembilan** [comment]
Thank you, but I have already made the fix here: https://github.com/spring-projects/spring-integration/pull/3981.
WDYT?

**Comment by kdebski85** [comment]
My approach might be slightly faster because:

1. I do not use synchronized
2. I do not use AtomicBoolean

Can I copy test from your PR?

**Comment by garyrussell** [comment]
See my comment on https://github.com/spring-projects/spring-integration/pull/3981

File: spring-integration-sftp/src/main/java/org/springframework/integration/sftp/session/DefaultSftpSessionFactory.java [hunk 1]
```diff
@@ -321,41 +321,50 @@ private ClientSession initClientSession() throws IOException {
...
 
 	private void initClient() throws IOException {
-		if (this.initialized.compareAndSet(false, true)) {
-			if (this.port <= 0) {
-				this.port = SshConstants.DEFAULT_PORT;
+		if (!this.initialized) {
+			synchronized (this) {
+				if (!this.initialized) {
+					doInitClient();
+					this.initialized = true;
```
Comment (artembilan) [inline spring-integration-sftp/src/main/java/org/springframework/integration/sftp/session/DefaultSftpSessionFactory.java:328]: @garyrussell , WDYT about this double-check solution instead?

Comment (garyrussell) [reply spring-integration-sftp/src/main/java/org/springframework/integration/sftp/session/DefaultSftpSessionFactory.java:328]: It's marginally better, I suppose, but performance is rarely an issue here because most people cache sessions.

That said, the patch looks more complicated than it really is, review with `?w=1`.

**Review by artembilan — CHANGES_REQUESTED** [review]
@kdebski85 ,

any chances to see a unit test to confirm that we don't have concurrency issue any more?
As we discussed before you can simply copy-paste a test I provide in my rejected PR: https://github.com/spring-projects/spring-integration/pull/3981/files#diff-ea9ddb7293f89610654c162b3b862b3b590008c3feb48e12ec2d57c69027d16eR96

Thanks

**Review by Krzysztof-Debski — APPROVED** [review]

**Comment by artembilan** [comment]
@kdebski85 ,

thank you for contribution and reasonable discussion; looking forward for more!
