### PR TITLE
GH-3421: Resolve `throws Exception;` in the API

### LINKED ISSUE #3421: Revise all the throws Exception; // NOSONAR
For example we have a code in the `WebSocketListener` like this:
```
void onMessage(WebSocketSession session, WebSocketMessage<?> message)
			throws Exception; // NOSONAR Remove in 5.2
```

so, all those `throws Exception` have to be removed.

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/3421

Remove `throws Exception;` from production code to honor the rule `Generic exceptions should never be thrown` which is enabled on SonarQube

* Rework affected usages to `try..catch` with throwing respective runtime exception or just logging
* Some other refactoring for the affected classes

### CODE REVIEW

File: spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java [hunk 1]
```diff
@@ -224,39 +224,54 @@ public List<String> getSubProtocols() {
...
+	public void afterSessionEnded(WebSocketSession session, CloseStatus closeStatus) {
 
 		if (isActive()) {
-			this.subProtocolHandlerRegistry.findProtocolHandler(session)
-					.afterSessionEnded(session, closeStatus, this.subProtocolHandlerChannel);
+			try {
+				this.subProtocolHandlerRegistry.findProtocolHandler(session)
+						.afterSessionEnded(session, closeStatus, this.subProtocolHandlerChannel);
+			}
+			catch (Exception ex) {
```
Comment (garyrussell) [inline spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java:257]: I think you'll need `// NOSONAR' for these to avoid Sonar complaining.

File: spring-integration-mail/src/main/java/org/springframework/integration/mail/transformer/MailToStringTransformer.java [hunk 2]
```diff
@@ -51,27 +52,34 @@ public void setCharset(String charset) {
...
-		if (content instanceof String) {
-			return this.getMessageBuilderFactory().withPayload((String) content);
+			return getMessageBuilderFactory().withPayload(payload);
 		}
-		if (content instanceof Multipart) {
-			ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
-			((Multipart) content).writeTo(outputStream);
-			return this.getMessageBuilderFactory().withPayload(
-					new String(outputStream.toByteArray(), this.charset));
+		catch (Exception ex) {
```
Comment (garyrussell) [inline spring-integration-mail/src/main/java/org/springframework/integration/mail/transformer/MailToStringTransformer.java:79]:
```suggestion
		catch (Exception ex) { // NOSONAR
```

File: spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java [hunk 3]
```diff
@@ -224,39 +224,54 @@ public List<String> getSubProtocols() {
...
+					accessor.setSessionId(session.getId());
+					accessor.setLeaveMutable(true);
+					accessor.setAcceptVersion("1.1,1.2");
+
+					Message<?> connectMessage =
+							MessageBuilder.createMessage(EMPTY_PAYLOAD, accessor.getMessageHeaders());
+					protocolHandler.handleMessageToClient(session, connectMessage);
+				}
+			}
+			catch (Exception ex) {
```
Comment (garyrussell) [inline spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java:243]:
```suggestion
			catch (Exception ex) { // NOSONAR
```

File: spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java (hunk 1 above)
Comment (garyrussell) [inline spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java:257]:
```suggestion
			catch (Exception ex) { // NOSONAR
```

**Review by garyrussell — CHANGES_REQUESTED** [review]

File: spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java (hunk 1 above)
Comment (artembilan) [reply spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java:257]: Why? What is that rule we would violate otherwise?

Comment (garyrussell) [reply spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java:257]: I might be confusing it with `catch (Throwable t)`; I guess leave as is.

Comment (artembilan) [reply spring-integration-websocket/src/main/java/org/springframework/integration/websocket/inbound/WebSocketInboundChannelAdapter.java:257]: I see. Probably you mean then this: https://rules.sonarsource.com/java/tag/error-handling/RSPEC-1181, which indeed doesn't talk about `catch Exception`

**Review by garyrussell — APPROVED** [review]
