### PR TITLE
GH-10137: Cache `session.list` result in the `AbstractInboundFileSynchronizer`

### LINKED ISSUE #10137: Shouldn't list remote file server each time max-fetch-size is reached
**In what version(s) of Spring Integration are you seeing this issue?**

all versions up to 6.5.x

**Describe the bug**

AbstractInboundFileSynchronizingMessageSource shoud list the remote server only once per poll.
However what happens here is each time you download max-fetch-size files, and max-message-per-poll isn't reached, then instead of working on the initial list until, it will list the remote server again, which is unnecessary and costs a lot of time.

Currently if you need a jdbc transaction per file downloaded and keep it to the end of the message flow, you need to use max-fetch-size=1, but then you end up having the remote server listed before downloading each single file, which slow down things considerably.

Chatgpt told me that AbstractRemoteFileStreamingMessageSource could be a solution to this, because it was maintaining a queue that was filled from remote file server list only when queue is empty.
But here I see the queue is cleared when maxFetchSize is reach, therefore it will trigger a remote file server list right after that

```
		if (maxFetchSize > 0 && this.fetched.get() >= maxFetchSize) {
			this.toBeReceived.clear();
			this.fetched.set(0);
		}
```
(https://github.com/spring-projects/spring-integration/blob/23154231f0c7a9fb5e3ebbcd4c8e7207d6e3df76/spring-integration-file/src/main/java/org/springframework/integration/file/remote/AbstractRemoteFileStreamingMessageSource.java#L219)

Therefore I see no solution to have a transaction per downloaded file and it's emitted message without having bad performances.

**To Reproduce**

Use a max-fetch-size=1

**Expected behavior**

Work on the remote file list until exhausted, before polling the server for a file list again.

**Sample**

Uncessary as code analysis shows the issue.

### PR DESCRIPTION
**Pull request by artembilan**
Fixes: https://github.com/spring-projects/spring-integration/issues/10137

When `maxFetchSize > 0`, the `AbstractInboundFileSynchronizer` performs unnecessary `Session.list()` every time.
Then we go over all those files to filter.
And only after filtering we apply the `maxFetchSize`.

* Add a cache for remote directory entries in the `AbstractInboundFileSynchronizer`
* Guard cache interaction with a `DefaultLockRegistry` per directory
* Rework `AbstractInboundFileSynchronizer.transferFilesFromRemoteToLocal()` to filter all the entries of the `Session.list()` on a first call. If `maxFetchSize > 0`, cache the remaining remote files

### CODE REVIEW

File: spring-integration-file/src/main/java/org/springframework/integration/file/remote/synchronizer/AbstractInboundFileSynchronizer.java [hunk 1]
```diff
@@ -86,6 +92,19 @@ public abstract class AbstractInboundFileSynchronizer<F>
...
 
+	private final DefaultLockRegistry lockRegistry = new DefaultLockRegistry();
+
+	@SuppressWarnings("serial")
+	private final Map<String, List<F>> fetchCache =
+			Collections.synchronizedMap(new LinkedHashMap<>(100, 0.75f, true) {
+
+				@Override
+				protected boolean removeEldestEntry(Map.Entry<String, List<F>> eldest) {
+					return size() > 100;
```
Comment (cppwfs) [inline spring-integration-file/src/main/java/org/springframework/integration/file/remote/synchronizer/AbstractInboundFileSynchronizer.java:103]: Do we want the 100 to be configurable?

File: spring-integration-file/src/test/java/org/springframework/integration/file/remote/synchronizer/AbstractRemoteFileSynchronizerTests.java [hunk 2]
```diff
@@ -114,12 +118,31 @@ public void testMaxFetchSizeSynchronizer() throws Exception {
...
-		sync.synchronizeToLocalDirectory(mock(File.class), 1);
+		File localDirectory = FileUtils.getTempDirectory();
+		sync.synchronizeToLocalDirectory(localDirectory, 1);
 		assertThat(count.get()).isEqualTo(1);
-		sync.synchronizeToLocalDirectory(mock(File.class), 1);
+
+		@SuppressWarnings("unchecked")
+		Map<String, List<String>> fetchCache = TestUtils.getPropertyValue(sync, "fetchCache", Map.class);
+		List<String> cachedFiles = fetchCache.get("testRemoteDirectory");
+		assertThat(cachedFiles).containsExactly("bar", "baz");
```
Comment (cppwfs) [inline spring-integration-file/src/test/java/org/springframework/integration/file/remote/synchronizer/AbstractRemoteFileSynchronizerTests.java]: Since we are replacing  `foo`.  We may go ahead and replace `bar` and `baz`.

File: src/reference/antora/modules/ROOT/pages/sftp/max-fetch.adoc [hunk 3]
```diff
@@ -26,6 +26,19 @@ Starting with version 5.1, the synchronizer can be provided with a `Comparator<?
 This is useful when restricting the number of files fetched with `maxFetchSize`.
 
 Starting with version 6.4, the `AbstractRemoteFileStreamingMessageSource` has now a convenient `clearFetchedCache()` API to remove references from cache for not processed remote files.
-The references stay in cache because polling configuration does not allow to process all of them in one cycle, and the target `SessionFactory` might be changed between polling cycles, e.g. via `RotatingServerAdvice`.
+The references stay in cache because polling configuration does not allow processing all of them in one cycle, and the target `SessionFactory` might be changed between polling cycles, e.g., via `RotatingServerAdvice`.
+
+Starting with version 7.0, the `AbstractInboundFileSynchronizer` caches a filtered `Session.list(remoteDirectory)` after applying a `maxFetchSize` slicing.
+The logic of the `AbstractInboundFileSynchronizer.transferFilesFromRemoteToLocal()` method is the following:
+
+- If `maxFetchSize > 0`, the lock is acquired against `remoteDirecy` to avoid race condition from different threads, when work is done around cache.
```
Comment (cppwfs) [inline src/reference/antora/modules/ROOT/pages/sftp/max-fetch.adoc]: `remoteDirectory` is misspelled.

File: src/reference/antora/modules/ROOT/pages/sftp/max-fetch.adoc [hunk 4]
```diff
@@ -26,6 +26,19 @@ Starting with version 5.1, the synchronizer can be provided with a `Comparator<?
...
+The performance degradation is minimal since all the later synchronizations deal only with in-memory cached leftover;
+- If no cache entry for the `remoteDirecy`, the `Session.list(remoteDirectory)` is called and all returned remote files are filtered;
```
Comment (cppwfs) [inline src/reference/antora/modules/ROOT/pages/sftp/max-fetch.adoc]: same here

File: src/reference/antora/modules/ROOT/pages/sftp/max-fetch.adoc [hunk 5]
```diff
@@ -26,6 +26,19 @@ Starting with version 5.1, the synchronizer can be provided with a `Comparator<?
...
+- the filtered result then sliced by the `maxFetchSize`;
+- then these file entries are being transferred to the local directory;
+- the rest of filtered remote files are cached for later synchronizations;
+- if there is a cache entry for the `remoteDirecy`, such a list is sliced `maxFetchSize` and iterated for the transfer to the local directory;
```
Comment (cppwfs) [inline src/reference/antora/modules/ROOT/pages/sftp/max-fetch.adoc]: same here.

"such a list is sliced `maxFetchSize`" could be rewritten as " such a list is sliced to the `maxFetchSize`".

File: src/reference/antora/modules/ROOT/pages/sftp/max-fetch.adoc [hunk 6]
```diff
@@ -26,6 +26,19 @@ Starting with version 5.1, the synchronizer can be provided with a `Comparator<?
...
+- if one of the transfers fails, the `filter` is reset from this remote file to the end of the filtered list.
```
Comment (cppwfs) [inline src/reference/antora/modules/ROOT/pages/sftp/max-fetch.adoc]: "if one of the transfers fails, the `filter` is reset from this remote file "
can be rewritten as 
"if one of the transfers fails, the `filter` is reset from from the failed remote file".

**Review by cppwfs — CHANGES_REQUESTED** [review]
Great work.

Just the usual nitpicks.

File: spring-integration-file/src/main/java/org/springframework/integration/file/remote/synchronizer/AbstractInboundFileSynchronizer.java (hunk 1 above)
Comment (artembilan) [reply spring-integration-file/src/main/java/org/springframework/integration/file/remote/synchronizer/AbstractInboundFileSynchronizer.java:103]: I don't think so.
The less choice for user, the better for this class instance state.
Why would one try to poll in parallel more than 100 remote directories?
