### PR TITLE
GH-8680: Check DB for table on start

### LINKED ISSUE #8680: Jdbc Backed QueueChannel fail fast if DB is not initialized properly
`JDBC` backed `MessageChannels` that aren't DB initialized properly are continuing to run on an infinite loop. It would help if it **fails fast** when the DB is not initialized properly

For more information, please refer the below SO

https://stackoverflow.com/questions/76697482/spring-integration-jdbc-backed-queuechannel-delayed-delivery

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/8680

If database is not initialized properly before application start, we may lose messages at runtime when we fail to insert data into DB

* Implement `SmartLifecycle` on `JdbcMessageStore`, `JdbcChannelMessageStore`, `JdbcMetadataStore`, and `DefaultLockRepository` to perform `SELECT COUNT` query in `start()` to fail fast if no required table is present.
* Refactor `AbstractJdbcChannelMessageStoreTests` into JUnit 5 and use `MySqlContainerTest` for more coverage
* Fix newly failed tests which had DB not initialized before
* Exclude `commons-logging` from `commons-dbcp2` dependency to avoid classpath conflict
* Document the new feature

### CODE REVIEW

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/store/JdbcMessageStore.java [hunk 1]
```diff
@@ -66,6 +68,10 @@
  * please consider using the channel-specific {@link JdbcChannelMessageStore} instead.
  * This implementation is intended for correlation components (e.g. {@code <aggregator>}),
  * {@code <delayer>} and similar.
+ * <p>
+ * This class implements {@link SmartLifecycle} and calls {@link #getMessageGroupCount()}
+ * on {@link #start()} to check if required tables are present in DB.
+ * The application context is going to fail starting if tables are not present.
```
Comment (garyrussell) [inline spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/store/JdbcMessageStore.java:74]:
```suggestion
 * The application context will fail to start if the table is not present.
```

File: src/reference/asciidoc/jdbc.adoc [hunk 2]
```diff
@@ -397,6 +398,9 @@ A common way to use these scripts is to reference them in a https://docs.spring.
 Note that the scripts are provided as samples and as specifications of the required table and column names.
 You may find that you need to enhance them for production use (for, example, by adding index declarations).
 
+Starting with version 6.2, the `JdbcMessageStore`, `JdbcChannelMessageStore`, `JdbcMetadataStore`, and `DefaultLockRepository` implement `SmartLifecycle` and perform `SELECT COUNT` query in their `start()` method to be sure that required table (according to the provided prefix) is present in the target database.
+If tables don't exist, the application context fails to start.
```
Comment (garyrussell) [inline src/reference/asciidoc/jdbc.adoc:402]:
```suggestion
Starting with version 6.2, the `JdbcMessageStore`, `JdbcChannelMessageStore`, `JdbcMetadataStore`, and `DefaultLockRepository` implement `SmartLifecycle` and perform a`SELECT COUNT` query, on their respective tables, in the `start()` method to ensure that the required table (according to the provided prefix) is present in the target database.
If the required table does not exist, the application context fails to start.
```

File: src/reference/asciidoc/whats-new.adoc [hunk 3]
```diff
@@ -45,3 +45,9 @@ See <<./web-sockets.adoc#websocket-client-container-attributes, WebSockets Suppo
 
 The `KafkaMessageSource` now extracts an `ErrorHandlingDeserializer` configuration from the consumer properties and re-throws `DeserializationException` extracted from failed record headers.
 See <<./kafka.adoc#kafka-inbound-pollable, Kafka Inbound Channel Adapter>> for more information.
+
+[[x6.2-jdbc]]
+=== JDBC Support Changes
+
+The `JdbcMessageStore`, `JdbcChannelMessageStore`, `JdbcMetadataStore`, and `DefaultLockRepository` implement `SmartLifecycle` and perform `SELECT COUNT` query in their `start()` method to be sure that required table (according to the provided prefix) is present in the target database.
```
Comment (garyrussell) [inline src/reference/asciidoc/whats-new.adoc:52]:
```suggestion
The `JdbcMessageStore`, `JdbcChannelMessageStore`, `JdbcMetadataStore`, and `DefaultLockRepository` implement `SmartLifecycle` and perform a`SELECT COUNT` query, on their respective tables, in the `start()` method to ensure that the required table (according to the provided prefix) is present in the target database.
```

**Review by garyrussell — CHANGES_REQUESTED** [review]

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java [hunk 4]
```diff
@@ -325,6 +340,23 @@ public void afterSingletonsInstantiated() {
...
+	public void stop() {
+		this.started.set(false);
+	}
+
+	@Override
+	public boolean isRunning() {
+		return this.started.get();
+	}
+
 	@Override
```
[the remark this answers is not in the document]
Comment (artembilan) [reply spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java:360]: Sounds good!
Let me take a look into this shortly!

**Comment by artembilan** [comment]
I guess when we are settled with this, we can expose such a property in Spring Boot to disable it globally, for example, for those applications which are working against stable environment with properly managed DB.
And it even can be `false` by default according to the `DataSourceInitializer` statement.

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java [hunk 5]
```diff
@@ -325,6 +346,41 @@ public void afterSingletonsInstantiated() {
 		this.serializableTransactionTemplate = new TransactionTemplate(this.transactionManager, transactionDefinition);
 	}
 
+	/**
+	 * The flag to perform database check query on start or not.
+	 * @param checkDatabaseOnStart false to not perform database check.
```
Comment (garyrussell) [inline spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java:351]:
```suggestion
	 * The flag to perform a database check query on start or not.
	 * @param checkDatabaseOnStart false to not perform the database check.
```

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/metadata/JdbcMetadataStore.java [hunk 6]
```diff
@@ -154,6 +174,42 @@ public void afterPropertiesSet() {
 		this.replaceValueByKeyQuery = String.format(this.replaceValueByKeyQuery, this.tablePrefix);
 		this.removeValueQuery = String.format(this.removeValueQuery, this.tablePrefix);
 		this.putIfAbsentValueQuery = String.format(this.putIfAbsentValueQuery, this.tablePrefix, this.tablePrefix);
+		this.countQuery = String.format(this.putIfAbsentValueQuery, this.tablePrefix);
+	}
+
+	/**
+	 * The flag to perform database check query on start or not.
+	 * @param checkDatabaseOnStart false to not perform database check.
```
Comment (garyrussell) [inline spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/metadata/JdbcMetadataStore.java:182]:
```suggestion
	 * The flag to perform a database check query on start or not.
	 * @param checkDatabaseOnStart false to not perform the database check.
```

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/store/JdbcChannelMessageStore.java [hunk 7]
```diff
@@ -411,6 +422,41 @@ public void afterPropertiesSet() {
 		this.jdbcTemplate.afterPropertiesSet();
 	}
 
+	/**
+	 * The flag to perform database check query on start or not.
+	 * @param checkDatabaseOnStart false to not perform database check.
```
Comment (garyrussell) [inline spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/store/JdbcChannelMessageStore.java:427]:
```suggestion
	 * The flag to perform a database check query on start or not.
	 * @param checkDatabaseOnStart false to not perform the database check.
```

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/store/JdbcMessageStore.java [hunk 8]
```diff
@@ -331,6 +343,41 @@ public void addAllowedPatterns(String... patterns) {
 		this.deserializer.addAllowedPatterns(patterns);
 	}
 
+	/**
+	 * The flag to perform database check query on start or not.
+	 * @param checkDatabaseOnStart false to not perform database check.
```
Comment (garyrussell) [inline spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/store/JdbcMessageStore.java:348]:
```suggestion
	 * The flag to perform a database check query on start or not.
	 * @param checkDatabaseOnStart false to not perform the database check.
```

**Review by garyrussell — CHANGES_REQUESTED** [review]

**Review by garyrussell — APPROVED** [review]
