### PR TITLE
GH-9291: Enhanced unlock() method of JdbcLock to verify successful unlocking

### LINKED ISSUE #9291: Enhanced unlock() method of JdbcLock to verify successful unlocking
**Expected Behavior**

* The `unlock()` method of `JdbcLock` should verify the execution result of releasing the lock ownership.
* If the ownership can not be removed due to data expiration, a `ConcurrentModificationException` should be thrown.
* `The RedisLock` implementation should also throw a `ConcurrentModificationException` in similar scenarios.

**Current Behavior**

* The `unlock()` method does not verify the execution result of releasing the lock ownership. 
* The `RedisLock` throws an `IllegalStateException` when attempting to release the lock after the ownership has expired.

**Context**

If the `unlock()` method does not verify the execution result of releasing the lock ownership, users might face concurrency issues without being notified. For example:
1. Process A and process B are operating in the same region. Process A acquires the distributed lock with lock_key: 'key'.
2. Due to prolonged work, the ownership of the lock held by process A expires.
3. Before process A releases the lock, process B also acquires the distributed lock with same lock_key.
4. When process A attempts to release the distributed lock, the current implementation does not inform the user that the integrity of data protected by this lock may have been compromised.

To address this, it is proposed that the `unlock()` method be enhanced to verify if the ownership of lock has been removed successfully.  If the ownership cannot be removed due to data expiration, a `ConcurrentModificationException` will be thrown.  This approach maintains the integrity of the distributed lock mechanism.

### PR DESCRIPTION
**Pull request by EddieChoCho**
Fixes: #9291
* Modify `unlock()` method of `JdbcLock`: if the lock ownership can not be removed due to data expiration, a `ConcurrentModificationException` should be thrown.
* Modify `unlock()` method of `RedisLock`: if the lock ownership can not be removed due to data expiration, a `ConcurrentModificationException` should be thrown.
* Maintain test cases

### CODE REVIEW

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/LockRepository.java [hunk 1]
```diff
@@ -41,8 +42,9 @@ public interface LockRepository extends Closeable {
 	/**
 	 * Remove a lock from this repository.
 	 * @param lock the lock to remove.
+	 * @return deleted or not.
 	 */
-	void delete(String lock);
+	boolean delete(String lock);
```
Comment (artembilan) [inline spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/LockRepository.java:47]: This is a breaking change in the public API.
Can we keep an old version of this method as `@Deprecated`?

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/JdbcLockRegistry.java [hunk 2]
```diff
@@ -305,12 +307,21 @@ public void unlock() {
...
+						else {
+							throw new ConcurrentModificationException();
+							// the lock is no longer owned by current process, the exception should be handle and rollback the execution result
+						}
 					}
 					catch (TransientDataAccessException | TransactionTimedOutException | TransactionSystemException e) {
 						// try again
 					}
+					catch (ConcurrentModificationException e) {
+						throw new ConcurrentModificationException("Lock was released in the store due to expiration. " +
```
Comment (artembilan) [inline spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/JdbcLockRegistry.java:322]: I'm not sure what is the reason to catch it here and re-throw immediately.
Why we just cannot include the message in the original one?

File: spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/lock/JdbcLockRegistryTests-context.xml [hunk 3]
```diff
@@ -24,8 +24,6 @@
 
 	<bean id="lockClient" class="org.springframework.integration.jdbc.lock.DefaultLockRepository">
 		<constructor-arg name="dataSource" ref="dataSource"/>
-		<property name="insertQuery"
-				  value="INSERT INTO INT_LOCK (REGION, LOCK_KEY, CLIENT_ID, CREATED_DATE) VALUES (?, ?, ?, ?)"/>
```
Comment (artembilan) [inline spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/lock/JdbcLockRegistryTests-context.xml:28]: There was a reason to have this in the test: https://github.com/spring-projects/spring-integration/issues/3866.

Even if it is the same value we have by default, it still covers a respective setter call.
So, please, consider to revert your change.
It is still not relevant to the purpose of this PR.

File: spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/lock/JdbcLockRegistryTests.java [hunk 4]
```diff
@@ -270,7 +272,12 @@ public void testTwoThreadsDifferentRegistries() throws Exception {
 					Thread.currentThread().interrupt();
 				}
 				finally {
-					lock2.unlock();
+					try {
+						lock2.unlock();
+					}
+					catch (ConcurrentModificationException ignored) {
```
Comment (artembilan) [inline spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/lock/JdbcLockRegistryTests.java:278]: Why do we need to catch it here, please?

File: spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/lock/JdbcLockRegistryTests.java [hunk 5]
```diff
@@ -502,6 +509,51 @@ void noTableThrowsExceptionOnStart() {
 		}
 	}
 
+	@Test
+	void testUnlock_lockStatusIsExpired_lockHasBeenAcquiredByAnotherProcess_ConcurrentModificationExceptionWillBeThrown() throws Exception {
```
Comment (artembilan) [inline spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/lock/JdbcLockRegistryTests.java:513]: We prefer the line length not more than `120` symbols.
Please, consider to shorten the name of this test method.
Plus we prefer a camel case for names.

File: spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisLockRegistry.java [hunk 6]
```diff
@@ -500,12 +501,12 @@ private void removeLockKey() {
 					return;
 				}
 				else if (Boolean.FALSE.equals(unlinkResult)) {
-					throw new IllegalStateException("Lock was released in the store due to expiration. " +
+					throw new ConcurrentModificationException("Lock was released in the store due to expiration. " +
```
Comment (artembilan) [inline spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisLockRegistry.java:504]: This is breaking change in the behavior.
We will have to mention this in the Migration Guide when we done with this PR: https://github.com/spring-projects/spring-integration/wiki

**Review by artembilan — CHANGES_REQUESTED** [review]
This also requires respective changes in the `lock-registry.adoc`, `redis.adoc` and `whats-new.adoc`.

The change is aimed for new `6.4` version.

Thanks

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/JdbcLockRegistry.java (hunk 2 above)
Comment (EddieChoCho) [reply spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/JdbcLockRegistry.java:322]: There is a catch block for catching general `Exception` in this method which will covert exceptions to `DataAccessResourceFailureException`.
To avoid `ConcurrentModificationException` be convert to `DataAccessResourceFailureException`, it needs to has it's own catch block.
Yes, we can include the message in the original one.

Comment (artembilan) [reply spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/JdbcLockRegistry.java:322]: Yeah... I see.
OK.
Let it be then like:
```
catch (ConcurrentModificationException e) {
    throw e;
}
```
And move that message to the original `throw` point.
With this `throw e;` we just don't create a new object.

File: spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/LockRepository.java (hunk 1 above)
Comment (artembilan) [reply spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/LockRepository.java:47]: After more thinking even if it is a breaking change from the API perspective, it is still save to call this method without checking its return.
So, having the fact that we still are changing behavior of the `RedisLockRegistry`, I probably will be OK to leave this as is and just mention in the Migration Guide.

**Review by artembilan — CHANGES_REQUESTED** [review]

File: spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/lock/JdbcLockRegistryTests.java (hunk 4 above)
Comment (artembilan) [reply spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/lock/JdbcLockRegistryTests.java:278]: Pushed.
Please, rebase your branch against the latest `main`.

File: src/reference/antora/modules/ROOT/pages/jdbc/lock-registry.adoc [hunk 7]
```diff
@@ -57,3 +57,4 @@ For example, an insert query for PostgreSQL hint can be configured like this:
 lockRepository.setInsertQuery(lockRepository.getInsertQuery() + " ON CONFLICT DO NOTHING");
 ----
 
+Starting with version 6.4, the `LockRepository.delete()` method return the result of removing ownership of a distributed lock. And the `JdbcLockRegistry.JdbcLock.unlock()` method throws `ConcurrentModificationException` if the ownership of the lock is expired.
```
Comment (artembilan) [inline src/reference/antora/modules/ROOT/pages/jdbc/lock-registry.adoc:60]: We prefer `One Sentence per Line` best practice: https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line

File: src/reference/antora/modules/ROOT/pages/whats-new.adoc [hunk 8]
```diff
@@ -32,7 +32,14 @@ The `LobHandler` (and respective API) has been deprecated for removal in Spring
 Respective option on `JdbcMessageStore` (and similar) have been deprecated as well.
 The byte array handling for serialized message is fully deferred to JDBC driver.
 
+The `LockRepository.delete()` method return the result of removing ownership of a distributed lock. And the `JdbcLockRegistry.JdbcLock.unlock()` method throws ConcurrentModificationException if the ownership of the lock is expired.
```
Comment (artembilan) [inline src/reference/antora/modules/ROOT/pages/whats-new.adoc:35]: DITTO.
Plus the `ConcurrentModificationException` is supposed to be a a code snippet like you do in other places.

**Review by artembilan — CHANGES_REQUESTED** [review]
So, all good. Just a couple nit-pics for the doc.

Thanks

**Comment by EddieChoCho** [comment]
Thank you for your feedback and the good reference! I've just pushed another commit.

**Comment by artembilan** [comment]
@EddieChoCho ,

thank you for contribution; looking forward for more!

I know, we have with you a `DistributedLock` feature outstanding 😄

**Comment by artembilan** [comment]
Here is a Migration Guide page we have talked about before: https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-6.3-to-6.4-Migration-Guide
