### PR TITLE
GH-8745: Add RFT.shouldMarkSessionAsDirty()

### LINKED ISSUE #8745: RemoteFileTemplate needlessly marks session dirty in case of no such file error
**In what version(s) of Spring Integration are you seeing this issue?**

6.1.3

**Describe the bug**

The issue applies to all classes which extend `org.springframework.integration.file.remote.RemoteFileTemplate`.  The description below uses `SftpRemoteFileTemplate` from `spring-integration-sftp` as an example.

`RemoteFileTemplate::execute` method marks session dirty in case of any exception.
It prevents session to be reused and makes `CachingSessionFactory` inefficient.
As a result, too many sessions are created and SFTP server may reject new connections.
Certain exceptions, like `SftpConstants.SSH_FX_NO_SUCH_FILE `, should not cause session to be marked dirty.

**To Reproduce**

1. Configure `DefaultSftpSessionFactory` to point to some valid SFTP
2. Wrap the factory with `CachingSessionFactory`
3. Configure `SftpRemoteFileTemplate` to use created `CachingSessionFactory`
4. Use `SftpRemoteFileTemplate::list` method with some path that does not exist on the server

**Expected behavior**

1. SftpRemoteFileTemplate::list throws exception (the current behaviour)
2. Session is not marked dirty and can be reused by further calls (currently it is marked dirty and cannot be reused)

Probably each class that extends `RemoteFileTemplate` should be able to define strategy for differentiating if an exception should mark session dirty.

**Workaround**
Use `SftpRemoteFileTemplate::exists` before each `SftpRemoteFileTemplate::list` (call `list` only when `exists` returns `true`)

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/8745

Not all errors caught in the `RemoteFileTemplate.execute()` are fatal to mark session as dirty and physically close the target session in the cache

* Introduce a `RemoteFileTemplate.shouldMarkSessionAsDirty()` to consult with an exception if it is really a fatal error to close the session in the end.
* Override `shouldMarkSessionAsDirty()` in the `RemoteFileTemplate` implementations to check statuses of respective protocol errors

**Cherry-pick to `6.1.x` & `6.0.x`**

### CODE REVIEW

File: spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java [hunk 1]
```diff
@@ -451,27 +451,42 @@ public <T> T execute(SessionCallback<F, T> callback) {
...
 			}
 		}
 	}
 
+	/**
+	 * Determine whether {@link Session#dirty()} should be called
+	 * in the {@link #execute(SessionCallback)} when exception is thrown from the callback.
+	 * By default, this method returns {@code true}.
+	 * Remote file protocol extensions can override this method to provide
+	 * a specific strategy against thrown exception, e.g. {@code file not found} error
```
Comment (garyrussell) [inline spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java:480]:
```suggestion
	 * a specific strategy against the thrown exception, e.g. {@code file not found} error
```

File: spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java [hunk 2]
```diff
@@ -451,27 +451,42 @@ public <T> T execute(SessionCallback<F, T> callback) {
...
+				catch (Exception ex) {
+					this.logger.debug("failed to close Session", ex);
 				}
 			}
 		}
 	}
 
+	/**
+	 * Determine whether {@link Session#dirty()} should be called
+	 * in the {@link #execute(SessionCallback)} when exception is thrown from the callback.
```
Comment (garyrussell) [inline spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java:477]:
```suggestion
	 * in the {@link #execute(SessionCallback)} when an exception is thrown from the callback.
```

File: spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java [hunk 3]
```diff
@@ -526,8 +540,7 @@ else if (payload instanceof byte[] || payload instanceof String) {
 			else if (payload instanceof InputStream) {
 				return new StreamHolder((InputStream) payload, "InputStream payload");
 			}
-			else if (payload instanceof Resource) {
-				Resource resource = (Resource) payload;
+			else if (payload instanceof Resource resource) {
```
Comment (garyrussell) [inline spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java:543]: In future, please refrain from this kind of (unrelated) refactoring when back porting is required (I will fix this time during back port).

File: spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java [hunk 4]
```diff
@@ -619,16 +632,7 @@ else if (!directoryPath.endsWith(this.remoteFileSeparator)) {
...
-
-		private final InputStream stream;
-
-		private final String name;
-
-		StreamHolder(InputStream stream, String name) {
-			this.stream = stream;
-			this.name = name;
-		}
+	private record StreamHolder(InputStream stream, String name) {
```
Comment (garyrussell) [inline spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java:636]: ditto

File: spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpRemoteFileTemplate.java [hunk 5]
```diff
@@ -82,29 +85,50 @@ protected <T> T doExecuteWithClient(final ClientCallback<FTPClient, T> callback)
...
-						return FtpRemoteFileTemplate.super.exists(path);
-
-					default:
-						throw new IllegalStateException("Unsupported 'existsMode': " +
-								FtpRemoteFileTemplate.this.existsMode);
-				}
+				return switch (FtpRemoteFileTemplate.this.existsMode) {
+					case STAT -> client.getStatus(path) != null;
+					case NLST -> !ObjectUtils.isEmpty(client.listNames(path));
+					case NLST_AND_DIRS -> FtpRemoteFileTemplate.super.exists(path);
```
Comment (garyrussell) [inline spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpRemoteFileTemplate.java:91]: and again

File: spring-integration-sftp/src/main/java/org/springframework/integration/sftp/session/SftpRemoteFileTemplate.java [hunk 6]
```diff
@@ -34,6 +39,20 @@
  */
 public class SftpRemoteFileTemplate extends RemoteFileTemplate<SftpClient.DirEntry> {
 
+	protected static final List<Integer> NOT_DIRTY_STATUSES =
```
Comment (garyrussell) [inline spring-integration-sftp/src/main/java/org/springframework/integration/sftp/session/SftpRemoteFileTemplate.java:42]:
```suggestion
	protected static final List<Integer> NOT_DIRTY_STATUSES = // NOSONAR
```

**Review by garyrussell — CHANGES_REQUESTED** [review]
Just a couple of doc polishing.

File: spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java (hunk 3 above)
Comment (garyrussell) [reply spring-integration-file/src/main/java/org/springframework/integration/file/remote/RemoteFileTemplate.java:543]: Doh; sorry - I didn't notice that we stop at 6.0.x.

**Review by garyrussell — APPROVED** [review]

**Comment by garyrussell** [comment]
...and cherry-picked after resolving minor conflicts.
