### PR TITLE
GH-3253: Scan BF hierarchy for BeanDefinition

### LINKED ISSUE #3253: Spring Integration Java DSL stops working when used in a Spring Batch modular configuration
**Describe the bug**
Spring Integration using the DSL produces a `NoSuchBeanDefinitionException:` No bean named `'javaDslInChildContextFlow.channel#0' available`, when the flow is configured within a child `ApplicationContext` configured in a modular Spring Batch setup.

The problem appears between Spring Integration releases `5.1.1` and `5.1.2` and is still present in the latest release.

A secondary observation is that the child `ApplicationContext` requires `@EnableIntegration` on it's `@Configuration` class, whereas previously it would work when specified on just the `@SpringBootApplication` class.

**To Reproduce**
Add an `IntegrationFlow` with the Java DSL to a Spring Batch child `ApplicationContext` while using a version of Spring Integration `5.1.2` or greater.

**Expected behavior**
The Integration flow is created/instantiated correctly.

**Sample**

Here's a link to a [minimal, reproducible sample](https://github.com/garethpowell/spring-integration-batch-problem).

There's a branch calling `working-version` that shows the same code working with the Spring Integration version downgraded to `5.1.1`

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects/spring-integration/issues/3253

The `IntegrationFlowBeanPostProcessor` uses a `containsBean()`
and then `getBeanDefinition()` to be sure that we don't override already
existing bean even if it is created in the parent(s) context.
The problem that `containsBean()` check the hierarchy, but `getBeanDefinition()`
doesn't.
So, we fail with `NoSuchBeanDefinitionException` if bean exists in the parent ctx

* Introduce an utility `IntegrationContextUtils.getBeanDefinition()` to
scan `BeanFactory` recursively for `BeanDefinition` for the requested `name`
* Use this tool in the `IntegrationFlowBeanPostProcessor` logic

**Cherry-pick to 5.2.x & 5.1.x**

### CODE REVIEW

**Comment by artembilan** [comment]
The fix has been tested in the provided sample application.

File: spring-integration-core/src/main/java/org/springframework/integration/context/IntegrationContextUtils.java [hunk 1]
```diff
@@ -212,4 +215,26 @@ public static Properties getIntegrationProperties(BeanFactory beanFactory) {
...
+	 * @throws NoSuchBeanDefinitionException if a {@link BeanDefinition} is not found
+	 * @since 5.1.10
+	 */
+	public static BeanDefinition getBeanDefinition(String name, ConfigurableListableBeanFactory beanFactory) {
+		try {
+			return beanFactory.getBeanDefinition(name);
+		}
+		catch (NoSuchBeanDefinitionException ex) {
+			BeanFactory parentBeanFactory = beanFactory.getParentBeanFactory();
+			if (parentBeanFactory instanceof ConfigurableListableBeanFactory) {
```
Comment (garyrussell) [inline spring-integration-core/src/main/java/org/springframework/integration/context/IntegrationContextUtils.java:233]: Why just one parent? Don't we need to recurse up the BF tree?

Comment (artembilan) [reply spring-integration-core/src/main/java/org/springframework/integration/context/IntegrationContextUtils.java:233]: Because the next `return getBeanDefinition(name, (ConfigurableListableBeanFactory) parentBeanFactory);` call is indeed recursive.

Not sure what am I missing...

Comment (garyrussell) [reply spring-integration-core/src/main/java/org/springframework/integration/context/IntegrationContextUtils.java:233]: Doh - not enough coffee.

**Comment by garyrussell** [comment]
Cherry-picked to 5.2.x and to 5.1.x after resolving conflicts.
